<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Vergleich von Mittelwerten – Skript zum Modul Angewandte Statistik</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05_correlation.html" rel="next">
<link href="./03_inference.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0ebfc3df13b83a4df80a9a05dab4e25a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04_compare_means.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Vergleich von Mittelwerten</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript zum Modul Angewandte Statistik</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Einführung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_prop_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Verteilungen von Wahrscheinlichkeiten</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Grundlagen der Inferenzstatistik</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_compare_means.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Vergleich von Mittelwerten</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_simple_linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Einfache lineare Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_multiple_linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_inf_cat_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inferenz für nominale Daten</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_logistic_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_poisson_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Einführung in die Überlebensanalyse</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linear Mixed Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#lernziele" id="toc-lernziele" class="nav-link active" data-scroll-target="#lernziele"><span class="header-section-number">4.1</span> Lernziele</a></li>
  <li><a href="#t-tests" id="toc-t-tests" class="nav-link" data-scroll-target="#t-tests"><span class="header-section-number">4.2</span> <span class="math inline">\(t\)</span>-Tests</a></li>
  <li><a href="#t-test-für-eine-einfache-stichprobe" id="toc-t-test-für-eine-einfache-stichprobe" class="nav-link" data-scroll-target="#t-test-für-eine-einfache-stichprobe"><span class="header-section-number">4.3</span> <span class="math inline">\(t\)</span>-Test für eine einfache Stichprobe</a>
  <ul class="collapse">
  <li><a href="#vorgehen" id="toc-vorgehen" class="nav-link" data-scroll-target="#vorgehen"><span class="header-section-number">4.3.1</span> Vorgehen</a></li>
  <li><a href="#konfidenzintervall-für-einen-mittelwert-schritt-für-schritt" id="toc-konfidenzintervall-für-einen-mittelwert-schritt-für-schritt" class="nav-link" data-scroll-target="#konfidenzintervall-für-einen-mittelwert-schritt-für-schritt"><span class="header-section-number">4.3.2</span> Konfidenzintervall für einen Mittelwert Schritt-für-Schritt:</a></li>
  <li><a href="#ein-stichproben-t-test-schritt-für-schritt" id="toc-ein-stichproben-t-test-schritt-für-schritt" class="nav-link" data-scroll-target="#ein-stichproben-t-test-schritt-für-schritt"><span class="header-section-number">4.3.3</span> Ein-Stichproben-<span class="math inline">\(t\)</span>-Test Schritt-für-Schritt:</a></li>
  <li><a href="#einstichproben-t-test-in-r" id="toc-einstichproben-t-test-in-r" class="nav-link" data-scroll-target="#einstichproben-t-test-in-r"><span class="header-section-number">4.3.4</span> Einstichproben-<span class="math inline">\(t\)</span>-Test in R</a></li>
  </ul></li>
  <li><a href="#t-test-für-verbundene-stichproben" id="toc-t-test-für-verbundene-stichproben" class="nav-link" data-scroll-target="#t-test-für-verbundene-stichproben"><span class="header-section-number">4.4</span> <span class="math inline">\(t\)</span>-Test für verbundene Stichproben</a>
  <ul class="collapse">
  <li><a href="#vorgehen-1" id="toc-vorgehen-1" class="nav-link" data-scroll-target="#vorgehen-1"><span class="header-section-number">4.4.1</span> Vorgehen</a></li>
  <li><a href="#gepaarter-t-test-in-r" id="toc-gepaarter-t-test-in-r" class="nav-link" data-scroll-target="#gepaarter-t-test-in-r"><span class="header-section-number">4.4.2</span> Gepaarter t-Test in R</a></li>
  </ul></li>
  <li><a href="#zweistichproben-t-test-für-unabhängige-stichproben" id="toc-zweistichproben-t-test-für-unabhängige-stichproben" class="nav-link" data-scroll-target="#zweistichproben-t-test-für-unabhängige-stichproben"><span class="header-section-number">4.5</span> Zweistichproben-t-Test für unabhängige Stichproben</a>
  <ul class="collapse">
  <li><a href="#konfidenzintervall-für-den-wahren-mittelwertsunterschied" id="toc-konfidenzintervall-für-den-wahren-mittelwertsunterschied" class="nav-link" data-scroll-target="#konfidenzintervall-für-den-wahren-mittelwertsunterschied"><span class="header-section-number">4.5.1</span> Konfidenzintervall für den wahren Mittelwertsunterschied</a></li>
  <li><a href="#vorgehen-2" id="toc-vorgehen-2" class="nav-link" data-scroll-target="#vorgehen-2"><span class="header-section-number">4.5.2</span> Vorgehen</a></li>
  </ul></li>
  <li><a href="#nicht-parametrische-tests" id="toc-nicht-parametrische-tests" class="nav-link" data-scroll-target="#nicht-parametrische-tests"><span class="header-section-number">4.6</span> Nicht-parametrische Tests</a>
  <ul class="collapse">
  <li><a href="#rang-methoden-rank-tests" id="toc-rang-methoden-rank-tests" class="nav-link" data-scroll-target="#rang-methoden-rank-tests"><span class="header-section-number">4.6.1</span> Rang-Methoden (rank tests)</a></li>
  <li><a href="#wilcoxon-vorzeichenrangtest" id="toc-wilcoxon-vorzeichenrangtest" class="nav-link" data-scroll-target="#wilcoxon-vorzeichenrangtest"><span class="header-section-number">4.6.2</span> Wilcoxon-Vorzeichenrangtest</a></li>
  <li><a href="#mann-whitney-u-test" id="toc-mann-whitney-u-test" class="nav-link" data-scroll-target="#mann-whitney-u-test"><span class="header-section-number">4.6.3</span> Mann-Whitney-U-Test</a></li>
  </ul></li>
  <li><a href="#anhang-hilfreiche-r-codes-für-mittelwertsvergleiche" id="toc-anhang-hilfreiche-r-codes-für-mittelwertsvergleiche" class="nav-link" data-scroll-target="#anhang-hilfreiche-r-codes-für-mittelwertsvergleiche"><span class="header-section-number">4.7</span> Anhang: hilfreiche <code>R</code> Codes für Mittelwertsvergleiche</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Vergleich von Mittelwerten</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>Dass die Sonne morgen aufgehen wird, ist eine Hypothese; und das heisst: wir <em>wissen</em> nicht, ob sie aufgehen wird.</p>
<p>— Ludwig Wittgenstein (Tractatus logico-philosophicus, 6.36311)</p>
</blockquote>
<section id="lernziele" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="lernziele"><span class="header-section-number">4.1</span> Lernziele</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Identifiziere Daten als <strong>gepaart bzw. verbunden</strong>, wenn zu jeder Beobachtungseinheit zwei Messungen der gleichen Variable vorliegen. Beispiele sind Prä-Post-Messungen (Messwiederholungen) bei einer Interventionsstudie oder die Preise für ein Buch in verschiedenen Buchhandlungen.</p></li>
<li><p>Berechne bei gepaarten Daten stets die <strong>Differenz zwischen den Datenpaaren</strong> (paarweise Differenzen). Damit können Teststatistiken (Prüfgrössen) und somit statistische Tests durchgeführt werden können.</p></li>
<li><p>Identifiziere Stichproben als <strong>unabhängig</strong>, wenn die Werte einer Stichprobe keine Informationen über die Werte der anderen Stichprobe enthalten. Dies ist z.B. bei kontrollierten Studien der Fall, bei denen Daten von Interventions- und Kontrollgruppen miteinander verglichen werden: Die Daten der Interventionsgruppe sind unabhängig von den Daten der Kontrollgruppe und enthalten keine Information über die Kontrollgruppe.</p></li>
<li><p>Beachte, dass beim Vergleich der Differenz von zwei Parametern, die Interpretation von Konfidenzintervallen stets eine vergleichende Aussage beinhaltet; erwähne, welche Gruppe den grösseren Parameterwert hat.</p></li>
<li><p>Verwerfe die Nullhypothese, wenn ein Konfidenzintervall für eine Differenz zwischen zwei Parametern den Wert 0 nicht enthält.</p></li>
<li><p>Gehe bei Hypothesentests stets systematisch vor:</p>
<ul>
<li><p>Lege die Prüfgrösse und das Signifikanzniveau fest, formuliere die Hypothesen und berechne die Kennzahlen.</p></li>
<li><p>Prüfe die Voraussetzungen (1) Unabhängigkeit der Daten, (2) Normalverteilung der Prüfgrösse und wähle je nach Ergebnis den richtigen Test aus.</p></li>
<li><p>Berechne das Konfidenzintervall für <span class="math inline">\(\mu\)</span> oder <span class="math inline">\(\delta=\mu_1-\mu_2\)</span>.</p></li>
<li><p>Berechne den Wert der Teststatistik (Prüfgrösse) und den P-Wert.</p></li>
<li><p>Formuliere eine Schlussfolgerung in leicht verständlicher Sprache.</p></li>
</ul></li>
<li><p>Führe z-Tests für eine und zwei Stichproben von Hand und in <code>R</code> durch (Berechnung des Konfidenzintervalls und des P-Wertes)</p></li>
<li><p>Führe einstichproben- und zweistichproben t-Tests in <code>R</code> durch und interpretiere alle Aspekte des R Outputs.</p></li>
</ol>
</div>
</div>
</section>
<section id="t-tests" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="t-tests"><span class="header-section-number">4.2</span> <span class="math inline">\(t\)</span>-Tests</h2>
<p><span class="math inline">\(t\)</span>-Tests sind <em>die</em> klassischen Hypothesentests. Sie gehören zur Gruppe der sog. <em>parametrischen</em> Tests. Damit parametrische Tests durchgeführt werden können, muss ein Schätzer (z.B. eine Mittelwertsdifferenz) normalverteilt sein. Aufgrund des zentralen Grenzwertsatzen wissen wir, dass dies bei grossen Stichproben der Fall ist. Bei kleinen Stichproben müssen die Daten selber in der Population annähernd normalverteilt sein.</p>
<p>Wenn diese Voraussetzung nicht erfüllt ist, können alternativ <em>nicht-parametrische</em> Tests verwendet werden. Verteilungsfreie, nicht-parametrische Testverfahren machen keine Annahmen über die Wahrscheinlichkeitsverteilung der untersuchten Variablen und sind deswegen auch anwendbar, wenn die Voraussetzungen an die Verteilungen nicht erfüllt sind, wie z.B. die Annahme einer Normalverteilung, oder wenn die Daten nicht mindestens intervallskaliert sind.</p>
<p>Parametrische Tests haben eine grössere Teststärke (Power) als nicht-parametrische Tests. Mit anderen Worten: Wenn tatsächlich ein Effekt in der Population vorliegt, haben parametrische Tests bessere Chancen, diesen Effekt auch zu entdecken. Zudem sind parametrische Tests einfacher zu interpretieren. Nicht-parametrische Tests prüfen oft eine etwas andere, nicht ganz intuitive Nullhypothese.</p>
<p>Im Zweifel gilt deshalb: Wenn immer möglich, parametrische Tests verwenden. Falls starke Evidenz dafür besteht, dass wichtige Voraussetzungen für ein parametrisches Verfahren nicht erfüllt sind, nicht-parametrische Verfahren wählen.</p>
<p>Nicht-parametrische Tests werden in diesem Skript zur Vollständigkeit erwähnt, gehören aber nicht zum Prüfungsstoff. Nichtparametrische Testverfahren werden am Ende dieses Kapitels vorgestellt.</p>
<section id="t-verteilung-versus-normalverteilung" class="level4" data-number="4.2.0.1">
<h4 data-number="4.2.0.1" class="anchored" data-anchor-id="t-verteilung-versus-normalverteilung"><span class="header-section-number">4.2.0.1</span> <span class="math inline">\(t\)</span>-Verteilung versus Normalverteilung</h4>
<p>Wie bei der Einführung von Konfidenzintervallen schon beschrieben, verwenden Statistikprogramme bei Annahme von normalverteilten Daten für die Berechnung von Wahrscheinlichkeiten die <span class="math inline">\(t\)</span>-Verteilung und nicht die Normalverteilung. Der zentrale Grenzwertsatz besagt, dass die Teststatisitk <span class="math inline">\(T\)</span> <span class="math display">\[
T=\frac{\bar{X}-\mu}{s/\sqrt{n}}
\]</span> bei <span class="math inline">\(n\)</span> gross näherungsweise normalverteilt ist, Wenn die Daten selbst normalverteilt sind, dann ist <span class="math inline">\(T\)</span> exakt <span class="math inline">\(t\)</span>-verteilt mit <span class="math inline">\(n−1\)</span> Freiheitsgraden, unabhängig von der Stichprobengrösse <span class="math inline">\(n\)</span>.</p>
<p>Da die <span class="math inline">\(t\)</span>-Verteilung bei grossem <span class="math inline">\(n\)</span> die Normalverteilung approximiert, ist sie auch bei nicht normalverteilten Daten und grossem <span class="math inline">\(n\)</span> eine gute Approximation. Statistikprogramme wie <code>R</code> verwenden daher standardmässig die <span class="math inline">\(t\)</span>-Verteilung, wenn die Populationsvarianz unbekannt ist – unabhängig davon, ob <span class="math inline">\(n\)</span> gross oder klein ist.</p>
</section>
</section>
<section id="t-test-für-eine-einfache-stichprobe" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="t-test-für-eine-einfache-stichprobe"><span class="header-section-number">4.3</span> <span class="math inline">\(t\)</span>-Test für eine einfache Stichprobe</h2>
<p>Im folgenden Beispiel wird auch die Berechnung von Konfidenzintervallen für $t-verteilte Daten besprochen. Der eigentliche <span class="math inline">\(t\)</span>-Test ist der letzte Schritt 4.</p>
<p><strong>Beispiel:</strong> Werden Volksläufer über die Jahre eher schneller oder langsamer? Für die Bearbeitung diese Frage liegen die Daten des Cherryblossom-Volkslaufs, der jeweils im Frühjahr in Washington, DC durchgeführt wird, vor. Die Laufstrecke ist 16.1 km (10 Meilen) lang (<a href="https://www.cherryblossom.org/">www.cherryblossom.org</a>).</p>
<p>Die durchschnittliche Laufzeit für alle Läufer:innen, die den Lauf 2006 beendet haben betrug 93.29 Minuten. Zum Vergleich liegt uns eine Zufallsstichprobe von 100 Läufer:innen vor, die am Lauf im Jahre 2012 teilgenommen haben (die Teilnehmerzahl betrug im Jahr 2012 16’924 Läufer:innen). Uns interessiert, ob die Läufer:innen zwischen 2006 und 2012 im Durchschnitt schneller oder langsamer geworden sind.</p>
<section id="vorgehen" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="vorgehen"><span class="header-section-number">4.3.1</span> Vorgehen</h3>
<p><strong>1. Hypothesen formulieren</strong></p>
<p>Der Vergleichswert aus dem Jahr 2006 ist in diesem Fall der sog. <em>Nullwert</em>: <span class="math inline">\(\mu_0 = 93.29\)</span>.</p>
<p><span class="math inline">\(H_0: \mu_{2012} = 93.29\)</span>, es gibt keinen Unterschied zwischen der durchschnittlichen Laufzeit von 2006 und dem Referenzwert.<br>
<span class="math inline">\(H_A: \mu_{2012} \neq 93.39\)</span>, es gibt einen Unterschied zwischen der durchschnittlichen Laufzeit von 2006 und dem Referenzwert.</p>
<p>Ist das eine einseitige oder eine zweiseitige <span class="math inline">\(H_A\)</span>?</p>
<p>Das Signifikanzniveau legen wir auf <span class="math inline">\(\alpha = 0.05\)</span> fest.</p>
<p><strong>2. Test-Voraussetzungen prüfen</strong></p>
<ul>
<li>Wir bestimmen Mittelwert und Standardabweichung und erstellen ein Histogramm für die Laufzeit.</li>
</ul>
<div class="cell" data-layout-align="center">
<div id="tbl-run12-desc" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-run12-desc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.1: Cherryblossom-Run 2012, n = 100
</figcaption>
<div aria-describedby="tbl-run12-desc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">m</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">s</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">100</td>
<td style="text-align: right;">95.87</td>
<td style="text-align: right;">16.66</td>
<td style="text-align: right;">95.01</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-cherryblossom-hist" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-cherryblossom-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_compare_means_files/figure-html/fig-plot-cherryblossom-hist-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-cherryblossom-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.1: Cherryblossom-Run 2012: Laufzeiten für die Stichprobe n = 100
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>Unabhängigkeit: Es handelt sich um eine Zufallsstichprobe von 100 aus 16924 Personen.</li>
<li>Die Verteilung der Daten im Histogramm ist nahezu normal (evtl. etwas linkssteil). Mit welchen Verfahren könnten Sie zusätzlich auf Normalverteilung prüfen?</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-qq-run12" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-qq-run12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_compare_means_files/figure-html/fig-plot-qq-run12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-qq-run12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.2: QQ-Plot fpr Cherryblossom-Run 2012, n = 100
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>3. Berechnung des 95%-Konfidenzintervalls für</strong> <span class="math inline">\(\mu\)</span></p>
<p><span class="math display">\[SE = \frac{s}{\sqrt{n}} = \frac{16.66}{\sqrt{100}}=1.66\]</span></p>
<p><span class="math display">\[CI_{95} = \bar{x} \pm t_{1-\frac{\alpha}{2}, df} \times SE\]</span></p>
<p>Wir verwenden hier für die Berechnung des 95%-Konfidenzintervalls die <span class="math inline">\(t\)</span>-Verteilung mit <span class="math inline">\(df = (100 - 1) = 99\)</span>. Weil die Stichprobe mit <span class="math inline">\(n\)</span> = 100 gross ist, würde eine Berechnung mit der <span class="math inline">\(z\)</span>-Verteilung praktisch zum gleichen Resultat führen.</p>
<p>Die Berechnung in <code>R</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># die Funktion qt() berechnet eine Quantile für eine bestimmte Fläche und </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># einen bestimmten Freiheitsgrad df</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(.<span class="dv">975</span>, <span class="at">df =</span> <span class="dv">99</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.984217</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span>                       <span class="co"># Stichprobenumfang </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fl">95.87</span>                     <span class="co"># Mittelwert</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fl">16.66</span>                     <span class="co"># Standardabweichung</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span> s<span class="sc">/</span><span class="fu">sqrt</span>(n)                <span class="co"># Standardfehler berechnen</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">qt</span>(.<span class="dv">975</span>, <span class="at">df =</span> <span class="dv">100-1</span>)      <span class="co"># t-Wert für 95%-CI und df = n-1 berechnen</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>CI95 <span class="ot">&lt;-</span> m <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> t <span class="sc">*</span> SE  <span class="co"># Grenzen für 95%-CI berechnen</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(CI95, <span class="dv">2</span>)                 <span class="co"># 95%-CI gerundet auf 2 Nachkommastellen ausgeben</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 92.56 99.18</code></pre>
</div>
</div>
<p>Das 95%-Konfidenzintervall für die durchschnittliche Laufzeit 2012 ist [92.56; 99.18]. Es beinhaltet den Durchschnittswert von 2006 von 93.29 Minuten und wir haben keine Evidenz gegen die Nullhypothese.</p>
<p><strong>4. Berechnung des P-Werts: Ein-Stichproben-t-Test</strong></p>
<p>Die Statistik ist die standardisierte Grösse</p>
<p><span class="math display">\[T = \frac{\bar{X} - \mu_0}{SE}.\]</span></p>
<p>Diese Grösse ist <span class="math inline">\(t\)</span>-verteilt mit <span class="math inline">\(n-1\)</span> Freiheitsgraden, <span class="math inline">\(T\sim t_{99}\)</span></p>
<p>Der <span class="math inline">\(t\)</span>-Wert ist dann:</p>
<p><span class="math display">\[t = \frac{\bar{x} - \mu_0}{SE}.\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span>                   <span class="co"># Stichprobenumfang der Stichprobe 2012</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fl">95.87</span>                 <span class="co"># Stichprobenmittelwert 2012</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fl">16.66</span>                 <span class="co"># Standardabweichung 2012</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fl">93.29</span>                <span class="co"># Nullwert 2006</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span> s<span class="sc">/</span><span class="fu">sqrt</span>(n)            <span class="co"># Standardfehler für den Stichprobenmittelwert 2012</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>t_wert <span class="ot">&lt;-</span> (m <span class="sc">-</span> mu)<span class="sc">/</span>SE      <span class="co"># Berechnung des t-Werts</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(t_wert, <span class="dv">3</span>)           <span class="co"># t-wert auf drei Stellen runden und ausgeben</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.549</code></pre>
</div>
</div>
<p>Der Wert der Teststatistik ist <span class="math inline">\(t = 1.549\)</span>. Den P-Wert können wir wieder mit <code>R</code> berechnen.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>p_wert <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span><span class="fu">pt</span>(t_wert, <span class="at">df =</span> <span class="dv">99</span>)) <span class="co"># P-Wert für eine zweiseitige Hypothese</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>p_wert <span class="ot">&lt;-</span> <span class="fu">round</span>(p_wert, <span class="dv">3</span>)            <span class="co"># P-Wert auf 3 Nachkommastellen runden</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>p_wert                                <span class="co"># P-Wert anzeigen</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.125</code></pre>
</div>
</div>
<p>Ein P-Wert von <span class="math inline">\(p\)</span> = 0.125 bedeutet, dass unter der Annahme, dass <span class="math inline">\(H_0\)</span> wahr ist, ein Ergebnis wie in unserer Stichprobe oder ein noch extremeres Ergebnis mit einer Wahrscheinlichkeit von 12.5 % vorkommt. <span class="math inline">\(p\)</span> = 0.12 ist grösser als unser Signifikanzniveau <span class="math inline">\(\alpha\)</span> = 0.05 und wir verwerfen die <span class="math inline">\(H_0\)</span> nicht.</p>
<p><strong>5. Schlussfolgerung formulieren</strong></p>
<p><em>Untersucht wurde die Frage, ob sich die durchschnittliche Laufzeit von Volksläufer:innen über die Jahre geändert hat. Als Nullwert wurde die durchschnittliche Laufzeit von 2006 von 93.29 Minuten angenommen. In einer Zufallsstichprobe n = 100 der Läufer:innen am Cherryblossom Run 2012 betrug die durchschnittliche Laufzeit 95.87 [92.56, 99.18] Minuten,</em> <span class="math inline">\(t_{99}\)</span> = 1.549, <span class="math inline">\(p\)</span> = 0.125. Die vorliegenden Daten liefern keine Evidenz dafür, dass sich die durchschnittlichen Laufzeiten zwischen 2006 und 2012 verändert haben.</p>
</section>
<section id="konfidenzintervall-für-einen-mittelwert-schritt-für-schritt" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="konfidenzintervall-für-einen-mittelwert-schritt-für-schritt"><span class="header-section-number">4.3.2</span> Konfidenzintervall für einen Mittelwert Schritt-für-Schritt:</h3>
<ol type="1">
<li>Vorbereitung: Berechne den <span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(s\)</span> und <span class="math inline">\(n\)</span> und lege das Konfidenzniveau fest (üblicherweise 95% = 0.95)</li>
<li>Voraussetzungen: Prüfe, ob die Voraussetzungen erfüllt sind, dass die Daten aus einer Normalverteilung stammen (QQ-Plot).</li>
<li>Berechnung: Wenn die Voraussetzungen erfüllt sind, berechne SE und berechne die Grenzen des Konfidenzintervalls mit den entsprechenden <span class="math inline">\(t\)</span>-Quantilen.</li>
<li>Schlussfolgerung: Interpretiere das Konfidenzintervall im Zusammenhang mit der Fragestellung.</li>
</ol>
<p>Code-Tipp: <span class="math inline">\(t\)</span>-Quantile lassen sich in <code>R</code> einfach berechnen:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># für ein 95%-Konfidenzintervall</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(.<span class="dv">975</span>, df)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># für ein 99%-Konfidenzintervall</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(.<span class="dv">995</span>, df)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># für ein 90%-Konfidenzintervall</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(.<span class="dv">95</span>, df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="ein-stichproben-t-test-schritt-für-schritt" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="ein-stichproben-t-test-schritt-für-schritt"><span class="header-section-number">4.3.3</span> Ein-Stichproben-<span class="math inline">\(t\)</span>-Test Schritt-für-Schritt:</h3>
<ol type="1">
<li>Vorbereitung: Identifiziere den für die Frage relevanten Parameter (die Prüfgrösse), formuliere die Hypothesen, lege das Signifikanzniveau <span class="math inline">\(\alpha\)</span> fest und berechne <span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(s\)</span> und <span class="math inline">\(n\)</span>.</li>
<li>Voraussetzungen: Prüfe, ob die Voraussetzungen erfüllt sind, dass die Daten aus einer normalverteilten Population stammen (QQ-Plot).</li>
<li>Wenn die Voraussetzungen erfüllt sind, berechne SE, den Wert der Teststatistik (den <span class="math inline">\(t\)</span>-Wert) und den P-Wert, brauche hierzu die <span class="math inline">\(t\)</span>-Verteilung mit <span class="math inline">\(df\)</span> Freiheitsgraden.</li>
<li>Schlussfolgerung: Beurteile den Hypothesentest, indem du den P-Wert mit dem Signifkanzniveau <span class="math inline">\(\alpha\)</span> vergleichst. Formuliere eine Schlussfolgerung im Zusammenhang mit der Fragestellung in leicht verständlicher Sprache.</li>
</ol>
<p>Code-Tipp: Der P-Wert lässt sich in <code>R</code> einfach berechnen:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># P-Wert für eine zweiseitige Hypothese berechnen</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(t_wert, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>))  <span class="co"># df = n - 1 = Stichprobenumfang - 1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="einstichproben-t-test-in-r" class="level3" data-number="4.3.4">
<h3 data-number="4.3.4" class="anchored" data-anchor-id="einstichproben-t-test-in-r"><span class="header-section-number">4.3.4</span> Einstichproben-<span class="math inline">\(t\)</span>-Test in R</h3>
<p>Für das Verständnis ist es gut, die oben beschriebenen Berechnungsschritte manuell nachzurechnen. In der Praxis kommt in der Regel jedoch Software zum Einsatz. Der t-Test ist in R implementiert und kann wie folgt durchgeführt werden:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> sample<span class="sc">$</span>time,               <span class="co"># sample$time = daten$variable</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="fl">93.29</span>,                    <span class="co"># mu = Nullwert</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>)     <span class="co"># zweiseitige Alternativhypothese</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  sample$time
t = 1.5489, df = 99, p-value = 0.1246
alternative hypothesis: true mean is not equal to 93.29
95 percent confidence interval:
 92.56457 99.17743
sample estimates:
mean of x 
   95.871 </code></pre>
</div>
</div>
<p>Wie Sie sehen, stimmt das Resultat bis auf Rundungsdifferenzen mit der manuellen Berechnung überein.</p>
</section>
</section>
<section id="t-test-für-verbundene-stichproben" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="t-test-für-verbundene-stichproben"><span class="header-section-number">4.4</span> <span class="math inline">\(t\)</span>-Test für verbundene Stichproben</h2>
<p>Von <em>verbundenen bzw. gepaarten Daten</em> sprechen wir dann, wenn zwei Variablen voneinander abhängig sind: Dies bedeutet, dass die Werte der einen Messung die Werte der anderen Messung beeinflussen. Das ist der Fall, wenn wir z.B. die Preise für ein Buch in verschiedenen Läden vergleichen oder wenn wir Messungen bei Individuen zu verschiedenen Zeitpunkten, z.B. vor und nach einer Intervention (Prä-Post-Messungen), durchführen.</p>
<p>Beispiel: In einer Studie wird untersucht, ob die Testpersonen mit einem neuen Schlafmittel länger schlafen als ohne Schlafmittel. Die Studie wird mit 20 Personen durchgeführt. Zuerst wird die Schlafdauer ohne Medikament (Baseline-Messung), dann die Schlafdauer mit Medikament (Follow-Up-Messung) gemessen.</p>
<p>Die Tabelle zeigt die Daten zu den ersten vier Probanden:</p>
<div class="cell" data-layout-align="center">
<div id="tbl-medi-sleep" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-medi-sleep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.2: Schlafmitteldaten, erste 4 Zeilen
</figcaption>
<div aria-describedby="tbl-medi-sleep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<caption>Schlafmitteldaten, erste 4 Zeilen</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Proband</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">ohne_Med</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mit_Med</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.28</td>
<td style="text-align: right;">5.83</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">5.69</td>
<td style="text-align: right;">4.69</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">4.81</td>
<td style="text-align: right;">4.43</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">5.90</td>
<td style="text-align: right;">6.49</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Jedem Probanden entsprechen zwei Messungen (Variablen): Eine für die Schlafdauer ohne und eine für die Schlafdauer mit Medikament. In diesem Fall liegen <em>gepaarte</em> Daten vor, da für jede Beobachtungseinheit zwei Messzeitpunkte vorliegen, die miteinander verglichen werden.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-medi-sleep-paired" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-medi-sleep-paired-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_compare_means_files/figure-html/fig-plot-medi-sleep-paired-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-medi-sleep-paired-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.3: Zusammenhang zwischen Schlafdauer mit und ohne Medikament
</figcaption>
</figure>
</div>
</div>
</div>
<p>Das Streudiagramm zeigt, dass die Schlafdauer mit Medikament in einem Zusammenhang mit der Schlafdauer ohne Medikament steht: Probanden, die ohne Medikament länger schlafen, schlafen auch mit Medikament länger.</p>
<p>Wenn wir den Effekt einer Intervention bei gepaarten Daten untersuchen, ist die Prüfgrösse die Differenz der Datenpaare, die sog. <strong>paarweisen Differenzen</strong>. Im vorliegenden Beispiel ist dies die Differenz zwischen der Schlafdauer mit und ohne Medikament. Wenn die Differenzen bei der Datenerhebung noch nicht berechnet wurden, erstellt man eine neue abgeleitete Variable und berechnet für jeden Probanden die paarweisen Differenzen. Dabei ist es wichtig eine konsistente Ordnung einzuhalten: Wenn wir uns für den Effekt des Medikamentes interessieren, berechnen wir die paarweisen Differenzen <span class="math inline">\(D_i\)</span> durch Subtraktion der Schlafdauer ohne Medikament <span class="math inline">\(X_1\)</span> von der Schlafdauer mit Medikament <span class="math inline">\(X_2\)</span>.</p>
<p><span class="math inline">\(D_i=X_{i2}-X_{i1}, i=1,\dots,n\)</span></p>
<p>Wenn das Medikament einen positiven Effekt auf die Schlafdauer hat, erhalten wir eine positive Differenz, wenn das Medikament die Schlafdauer verkürzt, erhalten wir eine negative Differenz. Für die Durchführung des t-Tests für gepaarte Daten verwenden wir als Prüfgrösse den Mittelwert der paarweisen Differenzen. Der Mittelwert der paarweisen Differenzen ist das Mass für den <strong>Effekt</strong> des Medikaments.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-sleep-medi-pairs" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sleep-medi-pairs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.3: Schlafmittel-Daten mit paarweisen Differenzen
</figcaption>
<div aria-describedby="tbl-sleep-medi-pairs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Proband</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">ohne_Med</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mit_Med</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">paarweise.Differenzen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.28</td>
<td style="text-align: right;">5.83</td>
<td style="text-align: right;">0.55</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">5.69</td>
<td style="text-align: right;">4.69</td>
<td style="text-align: right;">-1.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">4.81</td>
<td style="text-align: right;">4.43</td>
<td style="text-align: right;">-0.38</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">5.90</td>
<td style="text-align: right;">6.49</td>
<td style="text-align: right;">0.59</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Mit dem Mittelwert für paarweise Differenzen als Prüfgrösse haben wir die gleiche Situation, wie beim Einstichproben-<span class="math inline">\(t\)</span>-Test, nämlich einen Mittelwert, den wir gegen einen Nullwert vergleichen, und das weitere Vorgehen ist wie beim Einstichproben-<span class="math inline">\(t\)</span>-Test. Ein Einstichproben-<span class="math inline">\(t\)</span>-Test und ein <span class="math inline">\(t\)</span>-Test für verbundene Stichproben sind mathematisch identisch.</p>
<section id="vorgehen-1" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="vorgehen-1"><span class="header-section-number">4.4.1</span> Vorgehen</h3>
<p><strong>1. Hypothesen formulieren</strong></p>
<ul>
<li><p>Hypothesen formulieren</p>
<ul>
<li><span class="math inline">\(H_0: \mu_{D} = 0\)</span>, erwartete Differenz ist 0</li>
<li><span class="math inline">\(H_A: \mu_{D} \neq 0\)</span>, erwartete Differenz ungleich 0</li>
</ul></li>
</ul>
<p><strong>2. Test Voraussetzungen prüfen</strong>:</p>
<div class="cell" data-layout-align="center">
<div id="tbl-medi-sleep-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-medi-sleep-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.4: Kennzahlen zu Schlafmittel-Daten
</figcaption>
<div aria-describedby="tbl-medi-sleep-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">m</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">paarweise.Differenzen</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0.395</td>
<td style="text-align: right;">0.672</td>
</tr>
<tr class="even">
<td style="text-align: left;">ohne_Med</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">5.376</td>
<td style="text-align: right;">0.574</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mit_Med</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">5.771</td>
<td style="text-align: right;">0.953</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ul>
<li>Prüfe, ob die Voraussetzungen erfüllt sind, dass <span class="math inline">\(\bar{x}_{d}\)</span> aus einer annähernd normal verteilten Population stammt.
<ul>
<li>Prüfung auf Unabhängigkeit: Es handelt sich um eine Zufallsstichprobe.</li>
<li>Prüfung der Prüfgrösse (= paarweise Differenzen!) auf Normalverteilung (QQ-Plot unten)</li>
<li>Stichprobenumfang: Wenn die Prüfgrösse paarweise Differenzen sind, kann der t-Test ab n &gt; 12 angewendet werden, wenn die Daten annähernd normalverteilt sind. Wenn <span class="math inline">\(n\)</span> gross ist, ist der t-Test nahezu unbeschränkt durchführbar, unabhängig von der zugrundeliegenden Verteilung.</li>
</ul></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-qq-medi-sleep" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-qq-medi-sleep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_compare_means_files/figure-html/fig-plot-qq-medi-sleep-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-qq-medi-sleep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.4: Histogramm und QQ-Plot für paarweise Differenzen
</figcaption>
</figure>
</div>
</div>
</div>
<p>Im Histogramm sind die Daten leicht linksschief verteilt. Im QQ-Plot liegen die Punkte weitgehend auf einer Linie. Daher entscheiden wir für normalverteilte Daten.</p>
<p><strong>3. P-Wert und 95%-Konfidenzintervall berechnen.</strong></p>
<ul>
<li>Prüfgrösse (Statistik):</li>
</ul>
<p><span class="math inline">\(T=\frac{\bar{D}-0}{s_D/\sqrt{n}}=\frac{\bar{D}}{s_D/\sqrt{n}}\)</span></p>
<p>Diese Grösse ist <span class="math inline">\(t\)</span>-verteilt mit <span class="math inline">\(n-1\)</span> Freiheitsgraden, <span class="math inline">\(T\sim t_{19}\)</span></p>
<ul>
<li>Wert der Statistik:</li>
</ul>
<p><span class="math inline">\(t=\frac{\bar{d}}{s_D/\sqrt{n}}= \frac{0.395}{\frac{0.672}{\sqrt{20}}} = 2.629\)</span></p>
<ul>
<li>Signifikanzniveau <span class="math inline">\(\alpha\)</span> festlegen, üblicherweise <span class="math inline">\(\alpha = 0.05\)</span></li>
</ul>
<p>Den P-Wert für t und df = 20-1 können wir wieder mit <code>R</code> berechnen.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span><span class="fu">pt</span>(t, <span class="at">df =</span> <span class="dv">20-1</span>)) <span class="co"># P-Wert für zweiseitige Hypothese, t-Verteilung, df = 19</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Mit <span class="math inline">\(p\)</span> = 0.017 ist die Wahrscheinlichkeit für den beobachteten Effekt oder einen stärkeren Effekt kleiner als unser Signifkanzniveau <span class="math inline">\(\alpha = 0.05\)</span> und wir haben Evidenz dafür, dass wir die Nullhypothese zugunsten der Alternativhypothese verwerfen können.</p>
<p><span class="math display">\[CI_{95} = \bar{x} \pm t_{1-\frac{\alpha}{2}, df} \times SE = 0.395 \pm 2.093 \times 0.15\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(.<span class="dv">975</span>, <span class="dv">19</span>) <span class="co"># Quantile für t = 0.975 und df = 20- 1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.093024</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># P-Wert und 95%-CI berechnen</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> .<span class="dv">672</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> .<span class="dv">395</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span> s<span class="sc">/</span><span class="fu">sqrt</span>(n)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> (.<span class="dv">395</span> <span class="sc">-</span> <span class="dv">0</span>)<span class="sc">/</span>SE</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>p_wert <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span><span class="fu">pt</span>(t, <span class="at">df =</span> <span class="dv">20-1</span>))</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>p_out <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"P-Wert ="</span>, <span class="fu">round</span>(p_wert, <span class="dv">3</span>))</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>CI95 <span class="ot">&lt;-</span> m <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">qt</span>(.<span class="dv">975</span>, <span class="dv">19</span>) <span class="sc">*</span> SE</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>CI95 <span class="ot">&lt;-</span> <span class="fu">round</span>(CI95, <span class="dv">3</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>CI95_out <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"95% CI = ["</span>, CI95[<span class="dv">1</span>], <span class="st">", "</span>, CI95[<span class="dv">2</span>], <span class="st">"]"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Output</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>p_out</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "P-Wert = 0.017"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>CI95_out</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% CI = [0.08, 0.71]"</code></pre>
</div>
</div>
<p>Die Berechnung ergibt ein 95%-Konfidenzintervall für den Mittelwert der Differenz in der Schlafdauer von 0.395 [0.08, 0.71] Stunden. Das 95%-Konfidenzintervall enthält den Nullwert nicht und wir verwerfen die Nullhypothese zugunsten der Alternativhypothese.</p>
<p><strong>4. Schlussfolgerung formulieren</strong></p>
<p><em>Untersucht wurde der Einfluss eines Medikaments auf die Schlafdauer bei 20 Probanden. Das Medikament hat die Schlafdauer durchschnittlich um 0.395 [0.08 0.71] Stunden signifikant verlängert,</em> <span class="math inline">\(t(19)\)</span> = 2.629, <span class="math inline">\(p\)</span> = 0.017.</p>
</section>
<section id="gepaarter-t-test-in-r" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="gepaarter-t-test-in-r"><span class="header-section-number">4.4.2</span> Gepaarter t-Test in R</h3>
<p>Viel schneller ist man mit der implementierten <code>R</code>-Funktion für den t-Test:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variante 1: Als t-Test für gepaarte Stichproben</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> medi_data<span class="sc">$</span>mit_Med,        <span class="co"># Baseline-Data</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> medi_data<span class="sc">$</span>ohne_Med,       <span class="co"># Follow-Up-Data</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>,                <span class="co"># gepaarte Daten</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>)    <span class="co"># zweiseitige Alternativhypothese</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  medi_data$mit_Med and medi_data$ohne_Med
t = 2.6237, df = 19, p-value = 0.01672
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 0.07978913 0.70921087
sample estimates:
mean difference 
         0.3945 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variante 2: Als Einstichproben-t-Test mit der Variable paarweise.Differenzen</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> medi_data<span class="sc">$</span>paarweise.Differenzen,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  medi_data$paarweise.Differenzen
t = 2.6237, df = 19, p-value = 0.01672
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 0.07978913 0.70921087
sample estimates:
mean of x 
   0.3945 </code></pre>
</div>
</div>
<p>Der t-Test für gepaarte Stichproben berechnet zuerst die paarweisen Differenzen und ermittelt anschliessend die Teststatistik. Wenn man die paarweisen Differenzen im Datensatz berechnet hat, kann der Einstichproben-t-Test durchgeführt werden. Beide Varianten kommen zum exakt gleichen Ergebnis.</p>
</section>
</section>
<section id="zweistichproben-t-test-für-unabhängige-stichproben" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="zweistichproben-t-test-für-unabhängige-stichproben"><span class="header-section-number">4.5</span> Zweistichproben-t-Test für unabhängige Stichproben</h2>
<p>In diesem Abschnitt beschäftigen wir uns mit der Differenz von zwei Populationsmittelwerten <span class="math inline">\(\mu_1 - \mu_2\)</span> unter der Voraussetzung, dass die Stichproben unabhängig sind. Typisch sind Vergleiche zwischen zwei Gruppen bzw. Stichproben, z.B. kontrollierte Studien in denen Interventionsgruppe und Kontrollgruppe verglichen werden oder der Vergleich des Gewichts von Neugeborenen von rauchenden und nicht-rauchenden Müttern.</p>
<p>Die Formeln in diesem Abschnitt werden etwas komplizierter. In der Regel lassen wir die Software die Berechnungen durchführen und müssen nicht mit ihnen arbeiten. Für das Verständnis ist es aber gut, wenn Sie sich von diesen Formeln nicht abschrecken lassen. Sie sind einfacher, als sie zunächst aussehen!</p>
<section id="konfidenzintervall-für-den-wahren-mittelwertsunterschied" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="konfidenzintervall-für-den-wahren-mittelwertsunterschied"><span class="header-section-number">4.5.1</span> Konfidenzintervall für den wahren Mittelwertsunterschied</h3>
<p>Im Folgenden werden zuerst die theoretischen Grundlagen erarbeitet, anschliessend folgt ein Schritt-für-Schritt Beispiel für die Durchführung des Zweistichproben-t-Tests für unabhängige Stichproben.</p>
<p>Beispiel: Hat die Behandlung mit embryonalen Stammzellen (ESC) einen Effekt auf die Pumpfunktion des Herzens nach einem Herzinfarkt?</p>
<p>Die folgende Tabelle enthält die Kennzahlen aus einem Experiment, bei dem der Effekt von ESC bei Schafen, die einen Herzinfarkt erlitten hatten, geprüft wurde. Jedes dieser Schafe wurde randomisiert der Gruppe ESC oder der Kontrollgruppe zugewiesen, dann wurde ihre Herzkapazität (Auswurffraktion) gemessen <span class="citation" data-cites="ménard2005">(<a href="references.html#ref-ménard2005" role="doc-biblioref">Ménard et al. 2005</a>)</span>. Ein positiver Wert entspricht einer Steigerung der Auswurffraktion, was einer besseren Erholung entspricht. Unsere erste Aufgabe ist es, das 95%-Konfidenzintervall für den Effekt der ESCs auf die Herzfunktion im Vergleich zur Kontrollgruppe zu berechnen.</p>
<p>Codebook für den Datensatz <code>stemcell</code> .</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 86%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Beschreibung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">trtm</td>
<td style="text-align: left;">Behandlung: <code>ctrl</code> = Kontrolle, <code>esc</code>= embryonale Stammzellen</td>
</tr>
<tr class="even">
<td style="text-align: left;">before</td>
<td style="text-align: left;">Baseline: Auswurffraktion vor der Behandlung</td>
</tr>
<tr class="odd">
<td style="text-align: left;">after</td>
<td style="text-align: left;">Follow-Up: Auswurffraktion nach der Behandlung</td>
</tr>
</tbody>
</table>
<div class="cell" data-layout-align="center">
<div id="tbl-stem-cell" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stem-cell-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.5: Datensatz der ESC-Studie
</figcaption>
<div aria-describedby="tbl-stem-cell-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">trmt</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">before</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">after</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ctrl</td>
<td style="text-align: right;">35.25</td>
<td style="text-align: right;">29.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">ctrl</td>
<td style="text-align: right;">36.50</td>
<td style="text-align: right;">29.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ctrl</td>
<td style="text-align: right;">39.75</td>
<td style="text-align: right;">36.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">ctrl</td>
<td style="text-align: right;">39.75</td>
<td style="text-align: right;">38.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ctrl</td>
<td style="text-align: right;">41.75</td>
<td style="text-align: right;">37.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">ctrl</td>
<td style="text-align: right;">45.00</td>
<td style="text-align: right;">42.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ctrl</td>
<td style="text-align: right;">47.00</td>
<td style="text-align: right;">39.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">ctrl</td>
<td style="text-align: right;">52.00</td>
<td style="text-align: right;">45.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ctrl</td>
<td style="text-align: right;">52.00</td>
<td style="text-align: right;">52.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">esc</td>
<td style="text-align: right;">29.00</td>
<td style="text-align: right;">31.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">esc</td>
<td style="text-align: right;">29.50</td>
<td style="text-align: right;">43.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">esc</td>
<td style="text-align: right;">34.00</td>
<td style="text-align: right;">36.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">esc</td>
<td style="text-align: right;">35.00</td>
<td style="text-align: right;">41.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">esc</td>
<td style="text-align: right;">35.25</td>
<td style="text-align: right;">39.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">esc</td>
<td style="text-align: right;">42.50</td>
<td style="text-align: right;">40.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">esc</td>
<td style="text-align: right;">44.00</td>
<td style="text-align: right;">45.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">esc</td>
<td style="text-align: right;">49.25</td>
<td style="text-align: right;">55.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">esc</td>
<td style="text-align: right;">53.75</td>
<td style="text-align: right;">51.00</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Nach dem Erstellen einer abgeleiteten Variable <code>Differenz = after - before</code> berechnen wir die Kennzahlen für den Effekt der Behandlung.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-stem-cell-stat" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stem-cell-stat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.6: ESC-Daten: Effekt der Behandlung
</figcaption>
<div aria-describedby="tbl-stem-cell-stat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">trmt</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">m</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">esc</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">3.50</td>
<td style="text-align: right;">5.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">ctrl</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">-4.33</td>
<td style="text-align: right;">2.76</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Die Kennzahlen zeigen, dass die Auswurffraktion in der Kontrollgruppe CTRL um durchschnittlich -4.33% abgenommen und in der Interventionsgruppe ESC um 3.5% zugenommen hat.</p>
<p><span class="math display">\[\bar{x}_{int} - \bar{x}_{ctrl} = 3.5 - (-4.33) = 7.83\]</span></p>
<p>Für die Prüfung, ob wir die <span class="math inline">\(t\)</span>-Verteilung anwenden können, müssen wir die bisher verwendeten Voraussetzungen etwas erweitern:</p>
<ul>
<li><p><em>Unabhängigkeit:</em> Die Daten müssen sowohl zwischen den Stichproben als auch innerhalb der Stichproben unabhängig sein. Dies wird dadurch sichergestellt, dass die Beobachtungseinheiten randomisiert aus der Population ausgewählt und randomisiert den Gruppen Intervention oder Kontrolle zugeteilt werden.</p></li>
<li><p><em>Normalverteilung:</em> Die Daten müssen in beiden Stichproben normalverteilt sein. Wäre das <span class="math inline">\(n\)</span> gross, könnte man diese Voraussetzung vernachlässigen (zentraler Grenzwertsatz).</p></li>
</ul>
<p><span class="math inline">\(I\)</span> stehe für Intervention und <span class="math inline">\(C\)</span> für Kontrolle. Die Teststatistik oder Prüfgrösse <span class="math inline">\(T\)</span> ist der standardisierte Zwischengruppenunterschied</p>
<p><span class="math display">\[
T=\frac{(\bar{X}_I-\bar{X}_C)-\delta_0}{SE(\bar{X}_I-\bar{X}_C)}=\frac{(\bar{X}_I-\bar{X}_C)}{SE(\bar{X}_I-\bar{X}_C)},
\]</span> mit <span class="math inline">\(\delta_0=\mu_I-\mu_C=0\)</span> als dem postulierten Effekt unter <span class="math inline">\(H_0\)</span>. (<span class="math inline">\(\delta_0\)</span> muss aber nicht immer 0 sein!)</p>
<p>Für die Berechnung des Standardfehlers unterscheidet man zwischen homogenen Varianzen (normaler <span class="math inline">\(t\)</span>-Test) und heterogenen Varianzen (Welch-Test). Bei Annahme von <strong>homogenen Varianzen</strong> (<span class="math inline">\(\sigma_I^2=\sigma_C^2\)</span>), ist der Standardfehler <span class="math display">\[
SE(\bar{X}_I-\bar{X}_C)=\sqrt{\frac{1}{n_I}+\frac{1}{n_C}} \times\underbrace{
{\sqrt{\frac{(n_I-1)s^2_I+(n_C-1)s^2_C}{n_I+n_C-2}}}}_{s_{pooled}},
\]</span> mit <span class="math inline">\(s_{pooled}\)</span> als der gepoolten Standardabweichung.</p>
<p>Bei Annahme von <strong>heterogenen Varianzen</strong> (<span class="math inline">\(\sigma_I^2 \neq \sigma_C^2\)</span>) ist der Standardfehler <span class="math display">\[
SE(\bar{X_I}-\bar{X_C})=\sqrt{\frac{s_I^2}{n_I}+\frac{s_C^2}{n_C}}.
\]</span></p>
<p>Die Verteilung von <span class="math inline">\(T\)</span> ist wieder die <span class="math inline">\(t\)</span>-Verteilung: Bei homogenen Varianzen ist sie <span class="math inline">\(t\)</span>-verteilt mit <span class="math inline">\(n_I+n_C-2\)</span> Freiheitsgraden, <span class="math inline">\(T\sim t_{n_I+n_C-2}\)</span>. Bei heterogenen Varianzen gilt auch eine <span class="math inline">\(t\)</span>-Verteilung, aber mit komplexeren Freiheitsgraden (das macht dann <code>R</code> für uns.)</p>
<p>Für das Verständnis ist es gut, wenn Sie diese Berechnungen mindestens einmal von Hand durchführen. In der Praxis wird dafür Software verwendet, siehe unten.</p>
<p><strong>Prüfung der Voraussetzungen</strong></p>
<ul>
<li>Unabhängigkeit ist gegeben, da die Schafe randomisiert ausgewählt und den Gruppen Intervention oder Kontrolle zugeordnet wurden.</li>
<li>Prüfung der Normalverteilung anhand von Histogramm und QQ-Plot: Wir entscheiden für normalverteilte Daten.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-stem-cell-distr" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-stem-cell-distr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_compare_means_files/figure-html/fig-plot-stem-cell-distr-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-stem-cell-distr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.5: Histogramm und QQ-Plot für ESC- und Kontrollgruppe
</figcaption>
</figure>
</div>
</div>
</div>
<p>Anhand der Erläuterungen oben kann der Standardfehler für die Mittelwertsdifferenz wie folgt berechnet werden:</p>
<p><span class="math display">\[
s_{pooled}^2 = \frac{1}{16} \times (8 \times 5.17^2 + 8 \times 2.76^2) = 17.173
\]</span></p>
<p><span class="math display">\[
s_{pooled} = \sqrt{17.173} = 4.144
\]</span></p>
<p><span class="math display">\[
SE =4.144 \times \sqrt{\frac{1}{9} + \frac{1}{9}} = 1.954
\]</span></p>
<p>Die Anzahl Freiheitsgrade <span class="math inline">\(df\)</span> der <span class="math inline">\(t\)</span>-Verteilung ist <span class="math inline">\((n_I + n_C - 2) = (9 + 9 - 2) = 16\)</span>. Weil in diesem Fall die Gruppen gleich gross sind, also <span class="math inline">\(n_I = n_C\)</span>, hätte es die Berechnung von <span class="math inline">\(s_{pooled}\)</span> nicht gebraucht, sie wurde aber zur Vollständigkeit dennoch gezeigt, da im Allgemeinen <span class="math inline">\(n_1\neq n_2\)</span> sein muss.</p>
<p>Das 0.975-Quantil der <span class="math inline">\(t\)</span>-Verteilung mit <span class="math inline">\(df = 16\)</span> ist</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(.<span class="dv">975</span>, <span class="dv">16</span>)   </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.119905</code></pre>
</div>
</div>
<p>Durch Einsetzen können wir jetzt das 95%-Konfidenzintervall für die wahre Differenz des Effekts zwischen den beiden Stichproben berechnen:</p>
<p><span class="math display">\[CI_{95} = 7.83 \pm 2.12 \times 1.95 = [3.7; 11.96].\]</span></p>
<p>Das 95%-Konfidenzintervall beinhaltet Null nicht und wir haben somit Evidenz gegen <span class="math inline">\(H_0\)</span>. Die Behandlung mit embryonalen Stammzellen bei Schafen, die einen Herzinfarkt erlitten haben, verbessert die Pumpfunktion des Herzens im Durchschnitt um 7.83% [3.7%, 11.96%] im Vergleich zu keiner Behandlung. Dies entspricht einer statistisch signifikanten Verbesserung.</p>
<p>Die manuelle Berechnung stimmt bis auf Rundungsdifferenzen mit dem Resultat der <code>t.test()</code> Funktion in <code>R</code> überein:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Differenz <span class="sc">~</span> trmt, <span class="co"># Die Differenz wird nach Gruppe analysiert</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> stem_cell, <span class="co"># Die Daten kommen aus dem Datensatz stem_cell</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="co"># Zweiseitiger Test (defalut Einstellung)</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal =</span> <span class="cn">TRUE</span>) <span class="co"># Es wird angenommen, dass die Varianzen der beiden Stichproben gleich sind (siehe unten)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  Differenz by trmt
t = 4.0073, df = 16, p-value = 0.001016
alternative hypothesis: true difference in means between group esc and group ctrl is not equal to 0
95 percent confidence interval:
  3.689376 11.977290
sample estimates:
 mean in group esc mean in group ctrl 
          3.500000          -4.333333 </code></pre>
</div>
</div>
<p>Beim <code>t.test()</code> oben habe ich <code>R</code> mit <code>var.equal = TRUE</code> gesagt, dass die Standardabweichung in den beiden Populationen, aus der die Stichproben kommen, gleich ist. Homogene Stichprobenvarianzen sind im Prinzip eine weitere Voraussetzung für einen <span class="math inline">\(t\)</span>-Test. Warum sage ich im Prinzip? Weil es ein einfache Lösung gibt: Wenn man den <code>t.test()</code> ohne diese zusätzliche Information in R durchführt, dann korrigiert <code>R</code> automatisch, falls die Stichprobenvarianzen doch nicht homogen sind.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Differenz <span class="sc">~</span> trmt, <span class="co"># Die Differenz wird nach Gruppe analysiert</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> stem_cell) <span class="co"># Die Daten kommen aus dem Datensatz stem_cell</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Differenz by trmt
t = 4.0073, df = 12.225, p-value = 0.001678
alternative hypothesis: true difference in means between group esc and group ctrl is not equal to 0
95 percent confidence interval:
  3.582916 12.083750
sample estimates:
 mean in group esc mean in group ctrl 
          3.500000          -4.333333 </code></pre>
</div>
</div>
<p>In diesem Fall wird ein sogenannter <strong>Welch’s Test</strong> durchgeführt. Die Berechnung dieser Korrektur ist kompliziert, die Interpretation des Tests aber genau gleich, wie beim t-Test. Wir sehen, dass sich die beiden Testvarianten nur sehr geringfügig unterscheiden. Das ist oft der Fall. Wenn man nicht zu einer Berechnung von Hand gezwungen wird, empfiehlt sich, immer einen Welch’s Test durchzuführen. Somit entfällt die Voraussetzung bzgl. homogener Stichprobenvarianzen.</p>
</section>
<section id="vorgehen-2" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="vorgehen-2"><span class="header-section-number">4.5.2</span> Vorgehen</h3>
<p>Wir verwenden ein neues Beispiel.</p>
<p><strong>Frage:</strong> Hat es einen Einfluss auf das Geburtsgewicht von Neugeborenen, wenn schwangere Frauen rauchen? Wir prüfen diese Frage anhand eines Datensatzes, der eine Zufallsstichprobe von 150 Müttern und ihren Neugeborenen umfasst. Die Variable <code>smoke</code> erfasst, ob die Mutter während der Schwangerschaft geraucht hat oder nicht und die Variable <code>weight</code> gibt das Geburtsgewicht in g an. Die Raucherinnengruppe umfasst 50 Mütter, die Nichtraucherinnengruppe 100 Mütter.</p>
<p>Die Tabelle gibt die ersten 5 Einträge im Datensatz an:</p>
<div class="cell" data-layout-align="center">
<div id="tbl-bwt-smoke" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bwt-smoke-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.7: Datensatz Geburtsgewicht (g) und Raucherstatus
</figcaption>
<div aria-describedby="tbl-bwt-smoke-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">f_age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">m_age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">weeks</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">premature</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">visits</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">gained</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">weight</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">sex_baby</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">smoke</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">39</td>
<td style="text-align: left;">full term</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3121</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">smoker</td>
</tr>
<tr class="even">
<td style="text-align: left;">60</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">39</td>
<td style="text-align: left;">full term</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3402</td>
<td style="text-align: left;">female</td>
<td style="text-align: left;">nonsmoker</td>
</tr>
<tr class="odd">
<td style="text-align: left;">70</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">41</td>
<td style="text-align: left;">full term</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">3202</td>
<td style="text-align: left;">female</td>
<td style="text-align: left;">smoker</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">40</td>
<td style="text-align: left;">full term</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">4028</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">nonsmoker</td>
</tr>
<tr class="odd">
<td style="text-align: left;">71</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">41</td>
<td style="text-align: left;">full term</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">3175</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">smoker</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Das Vorgehen für die statistische Analyse ist wie bisher:</p>
<ol type="1">
<li>Vorbereitung: Identifiziere den für die Frage relevanten Parameter (die Prüfgrösse), formuliere die Hypothesen und lege das Signifikanzniveau <span class="math inline">\(\alpha\)</span> fest.</li>
<li>Prüfe, ob die Voraussetzungen (Unabhängigkeit der Daten, Normalverteilung) erfüllt sind.</li>
<li>Wenn die Voraussetzungen erfüllt sind, berechne <span class="math inline">\(SE\)</span>, das 95%-Konfidenzintervall, den <span class="math inline">\(t\)</span>-Wert und den P-Wert mit der entsprechenden <span class="math inline">\(t\)</span>-Verteilung.</li>
<li>Schlussfolgerung: Beurteile den Hypothesentest, indem du den P-Wert mit dem Signifkanzniveau <span class="math inline">\(\alpha\)</span> vergleichst. Formuliere eine Schlussfolgerung im Zusammenhang mit der Fragestellung in leicht verständlicher Sprache.</li>
</ol>
<p><strong>1. Hypothesen formulieren</strong></p>
<p>Hypothesen:<br>
- <span class="math inline">\(H_0: \mu_s = \mu_{ns}\)</span>, der Raucherstatus hat keinen Einfluss auf das Geburtsgewicht von Neugeboren.<br>
- <span class="math inline">\(H_A: \mu_s \neq \mu_{ns}\)</span>, der Raucherstatus hat einen Einfluss auf das Geburtsgewicht von Neugeboren.</p>
<p><strong>2. Voraussetzungen prüfen</strong></p>
<ul>
<li>Es handelt sich um eine Zufallsstichprobe, die Daten sind unabhängig.</li>
<li>Histogramm und QQ-Plot zeigen eine linksschiefe Verteilung für beide Gruppen. Weil <span class="math inline">\(n\)</span> gross ist, kann man gut mit dem zentralen Grenzwertsatz argumentieren, das die Mittelwertsdifferenzen normalverteilt sind.</li>
<li>Ob die Streuung der Daten in beiden Stichproben gleich ist interessiert uns nur, wenn wir kein <code>R</code> zur Verfügung haben. Wir haben aber <code>R</code> und führen grundsätzlich den <strong>Welch’s-Test</strong> durch, der eine Anpassung des Zweistichproben-t-Tests für ungleiche Varianzen macht.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-bwt-smoke-distr" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-bwt-smoke-distr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_compare_means_files/figure-html/fig-plot-bwt-smoke-distr-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-bwt-smoke-distr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.6: Histogramm und QQ-Plot für Geburtsgewicht nach Raucherstatus der Mutter”
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Berechnungen von Kennzahlen, SE, t-Wert und P-Wert</strong></p>
<div class="cell" data-layout-align="center">
<div id="tbl-desc-stat-bwt" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-desc-stat-bwt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.8: Kennzahlen für Geburtsgewicht (g) nach Raucherstatus der Mutter
</figcaption>
<div aria-describedby="tbl-desc-stat-bwt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">smoke</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">m</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">nonsmoker</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">3256.6</td>
<td style="text-align: right;">650.53</td>
</tr>
<tr class="even">
<td style="text-align: left;">smoker</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">3075.0</td>
<td style="text-align: right;">724.61</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Neugeborene von nicht-rauchenden Müttern sind im Durchschnitt <span class="math inline">\(3256.6 - 3075.0 = 181.6g\)</span> schwerer als von rauchenden Müttern.</p>
<p>Berechnung des Standardfehlers <span class="math inline">\(SE\)</span> der Prüfgrösse:</p>
<p><span class="math display">\[
s_{pooled}^2 = \frac{1}{148} \times (99 \times 651^2 + 49 \times 725^2) =  457513
\]</span></p>
<p><span class="math display">\[
S_{pooled} =  \sqrt{457513} = 676.397
\]</span></p>
<p><span class="math display">\[
SE=676.397 \times \sqrt{\frac{1}{100} + \frac{1}{50}} = 117.155
\]</span></p>
<p>Berechnung des 95%-Konfidenzintervalls. Das 0.975-Quantil ist</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(.<span class="dv">975</span>, <span class="at">df =</span> <span class="dv">148</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.976122</code></pre>
</div>
</div>
<p><span class="math display">\[CI_{95} = 181.6 \pm 1.976 \times 117.155 = [-49.9; 413.1]\]</span></p>
<p>Neugeborene von Nichtraucherinnen sind im Durchschnitt um 181.6 [-49.9; 413.1] schwerer als Neugeborene von Raucherinnen. Das 95%-Konfidenzintervall beinhaltet Null, d.h. kein Unterschied im Geburtsgewicht ist ein plausibler Wert, und wir haben keine Evidenz gegen die Nullhypothese.</p>
<p>Berechnung des t-Werts:</p>
<p><span class="math display">\[t = \frac{181.6}{117.155} = 1.55\]</span></p>
<p>Berechnung des P-Werts:</p>
<p>Die Anzahl Freiheitsgrade <span class="math inline">\(df = 100 + 50 - 2 = 148\)</span>: Wir können den P-Wert für <span class="math inline">\(t\)</span> wieder in einer Tabelle nachschlagen oder mit <code>R</code> berechnen:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fl">1.55</span>, <span class="at">df =</span> <span class="dv">148</span>)) <span class="co"># P-Wert für eine zweiseitige Hypothese und df = 148</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1232773</code></pre>
</div>
</div>
<p>Dieser P-Wert ist grösser als <span class="math inline">\(\alpha = 0.05\)</span> und wir haben keine ausreichende Evidenz, um die Nullhypothese zu verwerfen.</p>
<p>Schlussfolgerung: Untersucht wurde die Frage, ob Neugeborene von rauchenden Müttern ein anderes Geburtsgewicht haben als Neugeborene von nichtrauchtenden Müttern. Anhand der vorliegenden Daten konnte kein statistisch signifikanter Unterschied für das Geburtsgewicht von Neugeborenen rauchender und nichtrauchender Mütter festgestellt werden: Neugeborene von nichtrauchenden Müttern sind im Durchschnitt 181.6 [-49.9; 413.1] leichter als von nichtrauchenden Müttern, <span class="math inline">\(t(148) = 1.55, ~ p = 0.123\)</span>.</p>
<p>Der untenstehende Output zeigt, dass der t-Test bis auf Rundungsdifferenzen zum gleichen Resultat kommt:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  weight by smoke
t = 1.5511, df = 148, p-value = 0.123
alternative hypothesis: true difference in means between group nonsmoker and group smoker is not equal to 0
95 percent confidence interval:
 -49.7637 412.9637
sample estimates:
mean in group nonsmoker    mean in group smoker 
                 3256.6                  3075.0 </code></pre>
</div>
</div>
<p>Anmerkung: Dies ist ein vergleichsweise kleiner Datensatz; grössere Datensätze in aktuellen Studien liefern Evidenz dafür, dass Neugeborene von rauchenden Müttern ein geringeres Geburtsgewicht aufweisen als von nichtrauchenden Müttern. In den 70er-Jahren hat die Tabak-Industrie diese Tatsache sogar als Werbung mit dem Argument benutzt, dass Mütter kleinere Babies bei der Geburt bevorzugen <span class="citation" data-cites="reeves2008">(<a href="references.html#ref-reeves2008" role="doc-biblioref">Reeves and Bernstein 2008</a>)</span>.</p>
</section>
</section>
<section id="nicht-parametrische-tests" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="nicht-parametrische-tests"><span class="header-section-number">4.6</span> Nicht-parametrische Tests</h2>
<p>Die bisher besprochenen Testverfahren (t-Tests) können nur durchgeführt werden, wenn gewisse Voraussetzungen erfüllt sind:</p>
<ol type="1">
<li>Besonders bei kleineren Stichprobenumfängen müssen die Daten aus einer normalverteilten Population stammen. Wir kontrollieren das jeweils mittels Histogramm und QQ-Plot.</li>
<li>Der Stichprobenumfang sollte nicht zu klein sein (z.B. <span class="math inline">\(n &lt; 12\)</span>)</li>
<li>Es handelt sich um quantitative Daten.</li>
</ol>
<p>Es stellt sich nun die Frage, wie man Hypothesentests durchführt, wenn diese Bedingungen nicht erfüllt sind. Nicht-parametrische Tests sind nicht unumstritten, weil sie oft “nur” noch einen P-Wert und kein Konfidenzintervall liefern. Die Berechnugnen basieren meistens nicht auf Mittelwerten sondern auf Rängen, was die Interpretation schwierig macht. Zuletzt stellt sich bei sehr kleinen Stichproben ohnehin die Frage, ob es sinnvoll ist, inferenzstatistische Schlussfolgerungen zu ziehen. Hier werden zur Vollständigkeit die am meist gebrauchten nicht-parametrischen Verfahren vorgestellt. Es sei angemerkt, dass mittlerweile moderne Methoden existieren (ich bin z.B. Fan von <a href="https://lindeloev.github.io/tests-as-linear/">diesem Approach</a>).</p>
<p>Die nicht-parametrischen Verfahren sind nicht prüfungsrelevant.</p>
<section id="rang-methoden-rank-tests" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="rang-methoden-rank-tests"><span class="header-section-number">4.6.1</span> Rang-Methoden (rank tests)</h3>
<p>Rangtests spielen in der Klasse der nichtparametrischen Verfahren eine dominierende Rolle. Dabei ist die zu berechnende Teststatistik nur eine Funktion der rangierten (geordneten) Beobachtungen; die Beobachtungswerte selber werden nicht verwendet. Dies bedeutet, dass man nur die ordinale Information der Daten nutzt. Daher ist auch die Mindestanforderung an die Daten, dass sie qualitativ-ordinal skaliert sind.</p>
<p>Mathematisches Detail (nicht zu lernen): Die nichtparametrischen Methoden arbeiten mit diskreten Verteilungen. Die Berechnung von P-Werten erfolgt jedoch über eine sog. Approximation (Annäherung) an die Normalverteilung, welche eine kontinuierliche Verteilung ist. Bei der Aproximation einer diskreten an eine kontinuierliche Verteilung muss ein Korrekturfaktor <em>Kontinuitätskorrektur (engl. continuity correction)</em> eingeführt werden, der in der Ausgabe von Statistikprogrammen erwähnt wird.</p>
</section>
<section id="wilcoxon-vorzeichenrangtest" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2" class="anchored" data-anchor-id="wilcoxon-vorzeichenrangtest"><span class="header-section-number">4.6.2</span> Wilcoxon-Vorzeichenrangtest</h3>
<p>Der Wilcoxon-Vorzeichenrangtest wird für gepaarte Daten oder den Einstichprobenfall gewählt.</p>
<p>Beispiel: Wie Lange dauert eine Schwangerschaft? Und hängt die genaue Bestimmung von der Untersuchungsmethode ab? Zur Verfügung stehen zwei Methoden um die Schwangerschaftsdauer zu bestimmen: Einerseits die Methode der letzten Menstruationsperiode (LMP) und andererseits die Ultraschallmethode (US). Zufällig werden zehn schwangere Frauen ausgewählt und nach beiden Methoden die Schwangerschaftsdauer bestimmt. Die Untersuchung wird blindiert durchgeführt, so dass die LMP-Untersucher:innen die Ergebnisse der US-Untersucher:innen nicht kennen und umgekehrt.</p>
<p>Die Bestimmung der Schwangerschaftsdauer bei zehn schwangeren Frauen einer einfachen Stichprobe aus der gegebenen Population liefert folgende LMP und US Daten:</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ss-data" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ss-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.9: Daten für Schwangerschaftsdauer
</figcaption>
<div aria-describedby="tbl-ss-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">ID</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">LMP</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">US</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">LMPminusUS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">275</td>
<td style="text-align: right;">273</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">292</td>
<td style="text-align: right;">285</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">281</td>
<td style="text-align: right;">270</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">284</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">285</td>
<td style="text-align: right;">278</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">283</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">290</td>
<td style="text-align: right;">291</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">294</td>
<td style="text-align: right;">290</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">279</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">284</td>
<td style="text-align: right;">292</td>
<td style="text-align: right;">-8</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Wie können wir diese Daten interpretieren?</p>
<p>Als erstes berechnen wir die Kennzahlen und erstellen Grafiken zum Vergleich der beiden Bestimmungsmethoden.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ss-desc" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ss-desc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.10: kennzahlen Schwangerschaftsdauer
</figcaption>
<div aria-describedby="tbl-ss-desc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">name</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">m</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LMP</td>
<td style="text-align: right;">286.8</td>
<td style="text-align: right;">284.5</td>
<td style="text-align: right;">7.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">US</td>
<td style="text-align: right;">280.6</td>
<td style="text-align: right;">278.5</td>
<td style="text-align: right;">8.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-ss-desc" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-ss-desc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_compare_means_files/figure-html/fig-plot-ss-desc-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-ss-desc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.7: Boxplots für Schwangerschaftsdauer
</figcaption>
</figure>
</div>
</div>
</div>
<p>Der Vergleich von Mittelwert und Median und die Boxplots zeigen, dass die Daten linkssteil verteilt sind. Zudem ist der Stichprobenumfang mit n = 10 klein. Die Voraussetzungen für einen t-Test für gepaarte Daten sind zumindest fraglich.</p>
<p>Hypothesen:</p>
<p><span class="math inline">\(H_0: Median_{LMP} = Median_{US}\)</span>, die LMP- und die US-Methode ergeben die gleiche Schwangerschaftsdauer.<br>
<span class="math inline">\(H_A: Median_{LMP} \neq Median_{US}\)</span>, die LMP- und die US-Methode ergeben eine unterschiedliche Schwangerschaftsdauer.</p>
<blockquote class="blockquote">
<p>Merke: Beim Wilcoxon-Vorzeichenrangtest vergleichen wir Mediane und nicht Mittelwerte!</p>
</blockquote>
<p>Signifikanzniveau: <span class="math inline">\(\alpha = 0.05\)</span></p>
<p><strong>Vorgehen Wilcoxon-Vorzeichenrangtest</strong></p>
<p><em>Das Prinzip des Wilcoxon-Vorzeichen-Rangtests wird hier exemplarisch an einem Beispiel erläutert. Üblicherweise wird der Test in einem Statistikprogramm durchgeführt.</em></p>
<p>Gilt die Nullhypothese, so kann die Differenz der LMP- und US-Werte einer schwangeren Frau sowohl positiv wie auch negativ sein; weder positive noch negative Werte sollten überwiegen und die Differenzen sollten symmetrisch um Null verteilt sein. Der Wilcoxon-Vorzeichen-Rangtest prüft, ob die paarweisen Differenzen symmetrisch mit dem <em>Median</em> gleich Null verteilt sind.</p>
<p>Zur Durchführung des Tests werden diese Differenzen passend nach Rängen geordnet (rangiert). Es werden die absoluten Differenzen (Abstände zu Null) rangiert, ohne das Vorzeichen zu beachten. Ist eine Differenz Null, wird sie bei der Rangierung nicht verwendet und vom Stichprobenumfang n abgezogen.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ranks" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ranks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.11: Daten, Differenzen, Ränge und Vorzeichen der Differenzen der LMP- und US-Werte der Schwangerschaftsdauer
</figcaption>
<div aria-describedby="tbl-ranks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">ID</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">LMP</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">US</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">LMPminusUS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rang</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Vorzeichen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">275</td>
<td style="text-align: right;">273</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">plus</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">292</td>
<td style="text-align: right;">285</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">plus</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">281</td>
<td style="text-align: right;">270</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">plus</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">284</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">plus</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">285</td>
<td style="text-align: right;">278</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">plus</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">283</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">plus</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">290</td>
<td style="text-align: right;">291</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">minus</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">294</td>
<td style="text-align: right;">290</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">plus</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">279</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">plus</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">284</td>
<td style="text-align: right;">292</td>
<td style="text-align: right;">-8</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">minus</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-ranks" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-ranks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_compare_means_files/figure-html/fig-plot-ranks-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-ranks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.8: Punktediagramm der Schwangerschaftsdauer, US- und LMP-Werte mit Rängen
</figcaption>
</figure>
</div>
</div>
</div>
<p>Wenn die Differenzen symmetrisch um Null angeordnet sind, haben wir Evidenz dafür, dass <span class="math inline">\(H_0\)</span> wahr ist. Beachte, dass einige dieser Differenzen der Schwangerschaftsdauer gleich sind. Der Wert 7 kommt drei Mal vor. Diesen drei Werten sollten die Ränge 4, 5 und 6 zugeordnet werden. Ihr mittlerer Rang (Mittelwert von 4, 5 und 6) ist 5. Deshalb wird dieser mittlere Rang jedem der drei Werte zugeordnet.</p>
<p>Wir vergleichen jetzt die Summe der positiven Ränge mit der Summe der negativen Ränge. Sind diese beiden Rangsummen etwa gleich gross, haben wir keine Evidenz gegen die Nullhypothese, andernfalls werden wir die Nullhypothese ablehnen. Als einfache <strong>Teststatistik W</strong> verwenden wir Rangsumme der positiven Differenzen.</p>
<p>Summe der positiven Ränge: 2 + 3 + 5 + 5 + 5 + 8 + 9 + 10 = 47<br>
Summe der negativen Ränge: 1 + 7 = 8<br>
Teststatistik <span class="math inline">\(W\)</span> (in <code>R</code> Teststatistik <span class="math inline">\(V\)</span>) = 47</p>
<p>Berechnung des P-Werts für <span class="math inline">\(W = 47\)</span> und <span class="math inline">\(n = 10\)</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> <span class="dv">47</span>                            </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>p_Wert <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">psignrank</span>(W, <span class="at">n =</span> <span class="dv">10</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(p_Wert, <span class="dv">3</span>)            </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.037</code></pre>
</div>
</div>
<p><em>Schlussfolgerung: In einer Stichprobe von n = 10 schwangeren Frauen wurde die Frage untersucht, wie lange eine Schwangerschaft dauert und ob die Untersuchungsmethoden US und LMP zum gleichen Ergebnis kommen. Die Methode US ergibt gegenüber der Methode LMP eine um durchschnittlich um 6.2 Tage kürzere Schwangerschaftsdauer, Wilcoxon-Vorzeichenrangtest W = 47, p = 0.037.</em></p>
<p>Auch hier gibt es natürlich eine implementierte <code>R</code> Funktion:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(ss<span class="sc">$</span>LMP, ss<span class="sc">$</span>US, </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">alternative =</span> <span class="st">"two.sided"</span>, </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">correct =</span> <span class="cn">TRUE</span>)    <span class="co"># mit Kontinuitätskorrektur</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum exact test

data:  ss$LMP and ss$US
W = 70.5, p-value = 0.1277
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Anmerkung:</p>
<ul>
<li>Bei der Berechnung in <code>R</code> kann entspricht die ausgegebene <em>Teststatistik V</em> unserem Wert <span class="math inline">\(W\)</span>.</li>
<li>In <code>R</code> kann entschieden werden, ob die Kontinuitätskorrektur durchgeführt wird oder nicht. Bei unterschiedlichen Stichprobenumfängen sollte dies immer geschehen.</li>
</ul>
</section>
<section id="mann-whitney-u-test" class="level3" data-number="4.6.3">
<h3 data-number="4.6.3" class="anchored" data-anchor-id="mann-whitney-u-test"><span class="header-section-number">4.6.3</span> Mann-Whitney-U-Test</h3>
<p>Der Mann-Whitney-U-Test (= Wilcoxon-Rangsummentest) wird für den Vergleich von zwei Stichproben verwendet, wenn die Daten nicht normalverteilt sind.</p>
<p>Beispiel: Erreichen Studierende, die während einer Woche täglich 30 Minuten Statistikübungen machen, bessere Noten in einer Statistikprüfung? Für diese Studie wurden 15 Studierende zufällig ausgewählt und zufällig den Gruppen INT (n = 8) und CON (n = 7) zugeteilt. Beide Gruppen besuchten die Statistikvorlesung. Die Studierenden der Gruppe INT machten zusätzlich während einer Woche täglich 30 Min. Statistikübungen, die Gruppe CON machte keine Statistikübungen. Nach einer Woche wurde ein Statistiktest durchgeführt, der mit 0 bis 100 Punkten bewertet wurde.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-stat-ex-data" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stat-ex-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.12: Daten Statistikresultate
</figcaption>
<div aria-describedby="tbl-stat-ex-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">INT</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">CON</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">89, 92, 94, 96, 91, 99, 84, 90</td>
<td style="text-align: left;">88, 93, 95, 75, 72, 80, 81</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-stat-ex-desc" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stat-ex-desc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.13: Kennzahlen für Statistikresultate
</figcaption>
<div aria-describedby="tbl-stat-ex-desc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Gruppe</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">m</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CON</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">83.43</td>
<td style="text-align: right;">81.0</td>
<td style="text-align: right;">8.81</td>
</tr>
<tr class="even">
<td style="text-align: left;">INT</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">91.88</td>
<td style="text-align: right;">91.5</td>
<td style="text-align: right;">4.58</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Die deskriptive Analyse ergibt, dass die Interventionsgruppe im Durchschnitt 8.45 Punkte mehr erreicht als die Kontrollgruppe. Der Stichprobenumfang ist kleiner als 30 und die Daten sind leicht linkssteil verteilt; daher könnten die Voraussetzungen für einen t-Test nicht erfüllt sein.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-bp-stat-ex" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-bp-stat-ex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_compare_means_files/figure-html/fig-plot-bp-stat-ex-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-bp-stat-ex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.9: Boxplot für Statistikresultate
</figcaption>
</figure>
</div>
</div>
</div>
<p>Hypothesen</p>
<p><span class="math inline">\(H_0: P(INT &gt; CON) = P(CON &gt; INT)\)</span>, die Summen der Rangplätze von INT und CON unterscheiden sich nicht.<br>
<span class="math inline">\(H_A: P(INT &gt; CON) \neq P(CON &gt; INT)\)</span>, die Summen der Rangplätze von INT und CON unterscheiden sich.</p>
<p>Signifikanzniveau <span class="math inline">\(\alpha = 0.05\)</span></p>
<p>Für den Mann-Whitney-U-Test berechnen wir die <strong>Teststatistik U</strong>. <span class="math inline">\(U\)</span> ist der kleinere Wert von den beiden <span class="math inline">\(U_1\)</span> und <span class="math inline">\(U_2\)</span>, die wie folgt berechnet werden:</p>
<p><span class="math inline">\(U_1 = n_1 \times n_2+\frac{n_1 \times (n_1+1)}{2} - R_1\)</span><br>
<span class="math inline">\(U_2 = n_1 \times n_2+\frac{n_2 \times (n_2+1)}{2} - R_2\)</span></p>
<p>wobei, <span class="math inline">\(n_1\)</span> und <span class="math inline">\(n_2\)</span> die jeweiligen Stichprobenumfänge und <span class="math inline">\(R_1\)</span> und <span class="math inline">\(R_2\)</span> die Rangsummen der Gruppen 1 und 2 sind.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ranks-mw" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ranks-mw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;4.14: Statistikresultate mit Rängen
</figcaption>
<div aria-describedby="tbl-ranks-mw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Gruppe</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Punkte</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rang</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">INT</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">INT</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CON</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">INT</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CON</td>
<td style="text-align: right;">93</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">INT</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">INT</td>
<td style="text-align: right;">91</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">INT</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">INT</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">CON</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">INT</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">CON</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CON</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">CON</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CON</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">15</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="lightable-classic cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Gruppe</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rangsumme</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CON</td>
<td style="text-align: right;">72</td>
</tr>
<tr class="even">
<td style="text-align: left;">INT</td>
<td style="text-align: right;">48</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-ranks-mw" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-ranks-mw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_compare_means_files/figure-html/fig-plot-ranks-mw-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-ranks-mw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.10: Punktediagramm der Ränge für Statistikresultate
</figcaption>
</figure>
</div>
</div>
</div>
<p>Berechnung der Teststatistiken <span class="math inline">\(U_1\)</span> für die Interventionsgruppe und <span class="math inline">\(U_2\)</span> für die Kontrollgruppe</p>
<p><span class="math inline">\(U_1 = 8\times7+\frac{8(8+1)}{2} - 48 = 44\)</span><br>
<span class="math inline">\(U_2 = 8\times7+\frac{7(7+1)}{2} - 72 = 12\)</span></p>
<p>Unsere Teststatistik <span class="math inline">\(U\)</span> ist die kleinere der beiden Grössen <span class="math inline">\(U_1\)</span> und <span class="math inline">\(U_2\)</span>: <span class="math inline">\(U = 12\)</span></p>
<p>Berechnung des P-Werts mit <code>R</code></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>U <span class="ot">&lt;-</span> <span class="dv">12</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>p_Wert <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pwilcox</span>(U, <span class="at">m =</span> <span class="dv">8</span>, <span class="at">n =</span> <span class="dv">7</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>))</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>p_Wert</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07210567</code></pre>
</div>
</div>
<p>Da der P-Wert mit 0.0721 grösser als <span class="math inline">\(\alpha = 0.05\)</span> verwerfen wir die Nullhypothese nicht.</p>
<p><em>Schlussfolgerung: Untersucht wurde die Frage, ob Studierende, die während einer Woche täglich 30 Minuten Statistikübungen machen, bessere Punktzahlen erreichen als Studierende, die das nicht tun. Studierende, die während einer Woche täglich 30 Minunten Statistikübungen machen, erreichten in unserer Studie im Durchschnitt eine um 8.45 Punkte höhere Punktzahl in der Statistikprüfung, Mann-Whitney-U = 12, p = 0.0721. Damit liegt keine Evidenz dafür vor, dass sich die Prüfungsergebnisse im Durchschnitt zwischen den beiden Gruppen unterscheiden.</em></p>
<p>Ich hoffe die Ironie dieses Beispiels ist offensichtlich ;-)</p>
<p>In R kann der Mann Whitney U Test wie folgt durchgeführt werden:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  Punkte <span class="sc">~</span> Gruppe, <span class="at">data =</span> statex, </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum exact test

data:  Punkte by Gruppe
W = 12, p-value = 0.07211
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Wie einleitend bereits erwähnt, sind die Outputs der nicht-parametrischen Tests weit weniger informativ als jene der t-Tests: Man erhält keine Effektgrösse (man weiss nicht einmal, welche Gruppe favorisiert wird) und man erhält kein Konfidenzintervall.</p>
<section id="voraussetzungen-für-den-mann-whitney-u-test" class="level4" data-number="4.6.3.1">
<h4 data-number="4.6.3.1" class="anchored" data-anchor-id="voraussetzungen-für-den-mann-whitney-u-test"><span class="header-section-number">4.6.3.1</span> Voraussetzungen für den Mann-Whitney-U-Test:</h4>
<ul>
<li>Die Daten sind mindestens qualitativ-ordinal skaliert (Likert-Skalen, visuelle Analogskalen).</li>
<li>Es müssen zwei unabhängige Zufallsstichproben vorliegen.</li>
<li>Die Daten sollten gleich verteilt sein (z.B. beide linksschief), bzw. die beiden Verteilungen dürfen sich nur durch eine Verschiebung unterscheiden.</li>
</ul>
<p>Um zu prüfen, ob sich die beiden Stichprobendaten nur durch eine Verschiebung unterscheiden, erstellen Sie am besten einen Plot mit den kumulativen Wahrscheinlichkeitsverteilungen:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-cum-distr" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-cum-distr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_compare_means_files/figure-html/fig-plot-cum-distr-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-cum-distr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;4.11: Gleiche versus ungleiche Verteilung
</figcaption>
</figure>
</div>
</div>
</div>
<p>Während die beiden Verteilungen links in <a href="#fig-plot-cum-distr" class="quarto-xref">Abbildung&nbsp;<span>4.11</span></a> deutlich unterscheiden, unterscheiden sich die beiden Verteilungen rechts nur durch eine Verschiebung. Ein Mann Whitney U Test ist also nur in der Situation rechts angebracht.</p>
</section>
</section>
</section>
<section id="anhang-hilfreiche-r-codes-für-mittelwertsvergleiche" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="anhang-hilfreiche-r-codes-für-mittelwertsvergleiche"><span class="header-section-number">4.7</span> Anhang: hilfreiche <code>R</code> Codes für Mittelwertsvergleiche</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Zuerst werden zwei Variablen simuliert</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">0</span>) <span class="co"># Damit das Ergebnis reproduzierbar ist</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">10</span>, <span class="dv">2</span>) <span class="co"># 30 Werte aus einer Pupulation mit mu = 10 und sigma = 2</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">12</span>, <span class="dv">2</span>) <span class="co"># 30 Werte aus einer Pupulation mit mu = 12 und sigma = 2</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Die Werte von x und y darstellen</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(x, y, <span class="at">xaxt =</span> <span class="cn">NULL</span>)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>)) <span class="co"># Überschreiben der x-Achse</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Wenn x und y unabhängig sind: Zweistichproben t-Test</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, y, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(x, y, <span class="at">paired =</span> <span class="cn">FALSE</span>) <span class="co"># Nichtparametrische Alternative</span></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Wenn x und y abhängig (z.B. Prä-Post Messung): Gepaarter t-Test</span></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, y, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(x, y, <span class="at">paired =</span> <span class="cn">TRUE</span>) <span class="co"># Nichtparametrische Alternative</span></span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Ein gepaarter t-Test ist das Gleiche wie ein Einstichproben t-Test auf die Differenz:</span></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x<span class="sc">-</span>y)</span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Mu bei einem Einstichproben t-Test definieren:</span></span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x<span class="sc">-</span>y, <span class="at">mu =</span> <span class="sc">-</span><span class="dv">2</span>) <span class="co"># Unterscheidet sich die mittlere Differenz von -2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-ménard2005" class="csl-entry" role="listitem">
Ménard, Claudine, Albert A. Hagège, Onnik Agbulut, et al. 2005. <span>“Transplantation of Cardiac-Committed Mouse Embryonic Stem Cells to Infarcted Sheep Myocardium: A Preclinical Study.”</span> <em>The Lancet</em> 366 (9490): 1005–12. <a href="https://doi.org/10.1016/S0140-6736(05)67380-1">https://doi.org/10.1016/S0140-6736(05)67380-1</a>.
</div>
<div id="ref-reeves2008" class="csl-entry" role="listitem">
Reeves, Shane, and Ira Bernstein. 2008. <span>“Effects of maternal tobacco-smoke exposure on fetal growth and neonatal size.”</span> <em>Expert Review of Obstetrics &amp; Gynecology</em> 3 (6): 719–30. <a href="https://doi.org/10.1586/17474108.3.6.719">https://doi.org/10.1586/17474108.3.6.719</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03_inference.html" class="pagination-link" aria-label="Grundlagen der Inferenzstatistik">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Grundlagen der Inferenzstatistik</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05_correlation.html" class="pagination-link" aria-label="Korrelation">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Korrelation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>