<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Inferenz für nominale Daten – Skript zum Modul Angewandte Statistik</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09_logistic_regression.html" rel="next">
<link href="./07_multiple_linear-regression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0ebfc3df13b83a4df80a9a05dab4e25a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08_inf_cat_data.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inferenz für nominale Daten</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript zum Modul Angewandte Statistik</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Einführung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_prop_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Verteilungen von Wahrscheinlichkeiten</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Grundlagen der Inferenzstatistik</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_compare_means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Vergleich von Mittelwerten</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_simple_linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Einfache lineare Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_multiple_linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_inf_cat_data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inferenz für nominale Daten</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_logistic_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_poisson_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Einführung in die Überlebensanalyse</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linear Mixed Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#lernziele" id="toc-lernziele" class="nav-link active" data-scroll-target="#lernziele"><span class="header-section-number">8.1</span> Lernziele</a></li>
  <li><a href="#mathematische-grundlagen" id="toc-mathematische-grundlagen" class="nav-link" data-scroll-target="#mathematische-grundlagen"><span class="header-section-number">8.2</span> Mathematische Grundlagen</a>
  <ul class="collapse">
  <li><a href="#logarithmusfunktion-und-exponentialfunktion" id="toc-logarithmusfunktion-und-exponentialfunktion" class="nav-link" data-scroll-target="#logarithmusfunktion-und-exponentialfunktion"><span class="header-section-number">8.2.1</span> Logarithmusfunktion und Exponentialfunktion</a></li>
  <li><a href="#logistische-und-logit-funktion" id="toc-logistische-und-logit-funktion" class="nav-link" data-scroll-target="#logistische-und-logit-funktion"><span class="header-section-number">8.2.2</span> Logistische und Logit-Funktion</a></li>
  <li><a href="#rechenregeln" id="toc-rechenregeln" class="nav-link" data-scroll-target="#rechenregeln"><span class="header-section-number">8.2.3</span> Rechenregeln</a></li>
  </ul></li>
  <li><a href="#sec-der-chi2-test" id="toc-sec-der-chi2-test" class="nav-link" data-scroll-target="#sec-der-chi2-test"><span class="header-section-number">8.3</span> Der <span class="math inline">\(\chi^2\)</span>-Test</a>
  <ul class="collapse">
  <li><a href="#hypothesen-und-signifikanzniveau" id="toc-hypothesen-und-signifikanzniveau" class="nav-link" data-scroll-target="#hypothesen-und-signifikanzniveau"><span class="header-section-number">8.3.1</span> Hypothesen und Signifikanzniveau</a></li>
  <li><a href="#berechnen-der-erwarteten-werte-unter-der-nullhypothese" id="toc-berechnen-der-erwarteten-werte-unter-der-nullhypothese" class="nav-link" data-scroll-target="#berechnen-der-erwarteten-werte-unter-der-nullhypothese"><span class="header-section-number">8.3.2</span> Berechnen der erwarteten Werte unter der Nullhypothese</a></li>
  <li><a href="#voraussetzungen" id="toc-voraussetzungen" class="nav-link" data-scroll-target="#voraussetzungen"><span class="header-section-number">8.3.3</span> Voraussetzungen</a></li>
  <li><a href="#teststatistik" id="toc-teststatistik" class="nav-link" data-scroll-target="#teststatistik"><span class="header-section-number">8.3.4</span> Teststatistik</a></li>
  <li><a href="#interpretation-des-chi2-tests" id="toc-interpretation-des-chi2-tests" class="nav-link" data-scroll-target="#interpretation-des-chi2-tests"><span class="header-section-number">8.3.5</span> Interpretation des <span class="math inline">\(\chi^2\)</span>-Tests</a></li>
  <li><a href="#chi2-test-bei-variablen-mit-mehr-als-zwei-ausprägungen" id="toc-chi2-test-bei-variablen-mit-mehr-als-zwei-ausprägungen" class="nav-link" data-scroll-target="#chi2-test-bei-variablen-mit-mehr-als-zwei-ausprägungen"><span class="header-section-number">8.3.6</span> <span class="math inline">\(\chi^2\)</span>-Test bei Variablen mit mehr als zwei Ausprägungen</a></li>
  </ul></li>
  <li><a href="#sec-proportionen" id="toc-sec-proportionen" class="nav-link" data-scroll-target="#sec-proportionen"><span class="header-section-number">8.4</span> Proportionen</a>
  <ul class="collapse">
  <li><a href="#berechnungen-von-hand" id="toc-berechnungen-von-hand" class="nav-link" data-scroll-target="#berechnungen-von-hand"><span class="header-section-number">8.4.1</span> Berechnungen von Hand</a></li>
  <li><a href="#sec-berechnungen-von-proportionen-mit-r" id="toc-sec-berechnungen-von-proportionen-mit-r" class="nav-link" data-scroll-target="#sec-berechnungen-von-proportionen-mit-r"><span class="header-section-number">8.4.2</span> Berechnungen von Proportionen mit <code>R</code></a></li>
  </ul></li>
  <li><a href="#risiken" id="toc-risiken" class="nav-link" data-scroll-target="#risiken"><span class="header-section-number">8.5</span> Risiken</a>
  <ul class="collapse">
  <li><a href="#berechnungen-von-hand-1" id="toc-berechnungen-von-hand-1" class="nav-link" data-scroll-target="#berechnungen-von-hand-1"><span class="header-section-number">8.5.1</span> Berechnungen von Hand</a></li>
  <li><a href="#sec-berechnungen-von-rr-mit-r" id="toc-sec-berechnungen-von-rr-mit-r" class="nav-link" data-scroll-target="#sec-berechnungen-von-rr-mit-r"><span class="header-section-number">8.5.2</span> Berechnungen von RR mit <code>R</code></a></li>
  </ul></li>
  <li><a href="#odds" id="toc-odds" class="nav-link" data-scroll-target="#odds"><span class="header-section-number">8.6</span> Odds</a>
  <ul class="collapse">
  <li><a href="#berechnung-von-hand" id="toc-berechnung-von-hand" class="nav-link" data-scroll-target="#berechnung-von-hand"><span class="header-section-number">8.6.1</span> Berechnung von Hand</a></li>
  <li><a href="#berechnung-von-or-mit-r" id="toc-berechnung-von-or-mit-r" class="nav-link" data-scroll-target="#berechnung-von-or-mit-r"><span class="header-section-number">8.6.2</span> Berechnung von OR mit <code>R</code></a></li>
  </ul></li>
  <li><a href="#rr-versus-or" id="toc-rr-versus-or" class="nav-link" data-scroll-target="#rr-versus-or"><span class="header-section-number">8.7</span> RR versus OR</a></li>
  <li><a href="#die-verschiedenen-effektgrössen-im-überblick" id="toc-die-verschiedenen-effektgrössen-im-überblick" class="nav-link" data-scroll-target="#die-verschiedenen-effektgrössen-im-überblick"><span class="header-section-number">8.8</span> Die verschiedenen Effektgrössen im Überblick</a></li>
  <li><a href="#anhang-hilfreiche-r-codes-für-die-analyse-nominaler-daten" id="toc-anhang-hilfreiche-r-codes-für-die-analyse-nominaler-daten" class="nav-link" data-scroll-target="#anhang-hilfreiche-r-codes-für-die-analyse-nominaler-daten"><span class="header-section-number">8.9</span> Anhang: hilfreiche <code>R</code> Codes für die Analyse nominaler Daten</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-inferenz-fuer-nominale-daten" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inferenz für nominale Daten</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In diesem Kapitel lernen wir, wie Häufigkeiten von qualitativ-nominalen Variablen statistisch verglichen werden. Für die Analyse qualitativer Daten existieren zahlreiche statistische Werkzeuge, von denen hier nur eine Auswahl behandelt wird.</p>
<section id="lernziele" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="lernziele"><span class="header-section-number">8.1</span> Lernziele</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Verwende einen <span class="math inline">\(\chi^2\)</span>-Test, wenn die Unabhängigkeit von zwei nominalen Variablen geprüft werden soll.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Die zwei Variablen sind unabhängig.</li>
<li><span class="math inline">\(H_A\)</span>: Die zwei Variablen sind abhängig.</li>
</ul></li>
<li><p>Führe einen <span class="math inline">\(\chi^2\)</span>-Test in <code>R</code> durch und interpretiere alle Zeilen des Output.</p></li>
<li><p>Berechne Proportionen bzw. Risiken, Odds, Risk Ratios und Odds Ratios auf Basis von Vierfeldertabellen von Hand und mit Hilfe von <code>R</code>.</p></li>
<li><p>Rechne Odds in Wahrscheinlichkeiten/Proportionen um und umgekehrt:</p>
<p><span class="math display">\[
P = \frac{Odds}{1+Odds}
\]</span></p>
<p>und</p>
<p><span class="math display">\[
Odds = \frac{P}{1-P}.
\]</span></p></li>
<li><p>Berechne den Standardfehler und Konfidenzintervalle für Proportionen, Risk Ratios und Odds Ratios unter Verwendung der Normalapproximation.</p></li>
<li><p>Führe den Proportionstest für eine und zwei unabhängige Stichproben in <code>R</code> durch und interpretiere alle Zeilen des Outputs.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\pi = \pi_0\)</span>, bzw. <span class="math inline">\(\pi_1 = \pi_2\)</span> (die Proprotionen unterscheiden sich nicht)</li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(\pi \ne \pi_0\)</span>, bzw. <span class="math inline">\(\pi_1 \ne \pi_2\)</span> (die Proprotionen unterscheiden sich)</li>
</ul></li>
<li><p>Führe Tests für Risk Ratios und Odds Ratios in <code>R</code> durch und interpretiere den Output.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(RR = 1\)</span>, bzw. <span class="math inline">\(OR = 1\)</span> (das Odds Ratio, bzw. das Risk Ratio unterscheidet sich nicht von 1)</li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(RR \ne 1\)</span>, bzw. <span class="math inline">\(OR \ne 1\)</span> (das Odds Ratio, bzw. das Risk Ratio unterscheidet sich von 1)</li>
</ul></li>
</ol>
</div>
</div>
</section>
<section id="mathematische-grundlagen" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="mathematische-grundlagen"><span class="header-section-number">8.2</span> Mathematische Grundlagen</h2>
<p>Wir brauchen für die kommenden Inhalte einige mathematische Grundlagen bezüglich wichtiger Funktionen.</p>
<section id="logarithmusfunktion-und-exponentialfunktion" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="logarithmusfunktion-und-exponentialfunktion"><span class="header-section-number">8.2.1</span> Logarithmusfunktion und Exponentialfunktion</h3>
<p><strong>Logarithmus</strong> <span class="math inline">\(\log(\cdot)\)</span> und <strong>Exponentialfunktion</strong> <span class="math inline">\(\exp(\cdot)\)</span> Funktion sind zentral in der Wissenschaft und in der Statistik.</p>
<p><span class="math display">\[
\log(x): \mathbb{R^+}\rightarrow \mathbb{R}: y=\log(x)
\]</span> <span class="math display">\[
\exp(x): \mathbb{R}\rightarrow \mathbb{R^+}: y=\exp(x)
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_inf_cat_data_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_inf_cat_data_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="logistische-und-logit-funktion" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="logistische-und-logit-funktion"><span class="header-section-number">8.2.2</span> Logistische und Logit-Funktion</h3>
<p>Wenn wir später zur logistischen Regression kommen, werden wir die <strong>Logistische</strong> (<span class="math inline">\(\text{logistic}(\cdot)\)</span>) und <strong>Logit</strong>-Funktion (<span class="math inline">\(\text{logit}(\cdot)\)</span>) häufig antreffen. Eine ist die Umkehrfunktion der anderen:</p>
<p><span class="math display">\[
\text{logit}(x):[0,1]\rightarrow \mathbb{R},\quad x \mapsto
    \log\frac{x}{1-x}.
\]</span></p>
<p><span class="math display">\[
\text{logistic}(x): \mathbb{R} \rightarrow [0,1],\quad x \mapsto
    \frac{\exp(x)}{\exp(x)+1}.
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_inf_cat_data_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_inf_cat_data_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="rechenregeln" class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="rechenregeln"><span class="header-section-number">8.2.3</span> Rechenregeln</h3>
<p>Beachten Sie im Folgenden die überaus wichtigen Rechenregeln bezüglich der <span class="math inline">\(\log\)</span> und <span class="math inline">\(\exp\)</span>-Funktion. Sie werden uns auf Schritt und Tritt verfolgen:</p>
<p><span class="math display">\[
\begin{aligned}
\log(a \times b) &amp;= \log(a) + \log(b)\\
\log(a /b) &amp;= \log(a) - \log(b)\\
\exp(a + b) &amp;= \exp(a) \times \exp(b)\\
\quad \exp(a-b) &amp;= \exp(a)/\exp(b)
\end{aligned}
\]</span></p>
</section>
</section>
<section id="sec-der-chi2-test" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="sec-der-chi2-test"><span class="header-section-number">8.3</span> Der <span class="math inline">\(\chi^2\)</span>-Test</h2>
<p>Der <span class="math inline">\(\chi^2\)</span>-Test ist einer der ältesten Hypothesentests. Er wurde um 1900 von <a href="https://en.wikipedia.org/wiki/Karl_Pearson">Karl Pearson</a> entwickelt und später von <a href="https://en.wikipedia.org/wiki/Ronald_Fisher">Sir Ronald Fisher</a> verfeinert. Der <span class="math inline">\(\chi^2\)</span>-Test prüft, ob eine beobachtete Häufigkeitsverteilung einer nominalen Variable einer erwarteten Verteilung entspricht.</p>
<p>Beispiel: Hatten die Eltern von Kindern mit Allergien selber häufiger Allergien als die Eltern von Kindern ohne Allergien? Für diese Fragestellung wurde eine Zufallsstichprobe von 38 Kindern und deren Eltern zu ihrem Allergiestatus befragt. Codiert wurden die Daten mit <em>0 = keine Allergie</em> und <em>1 = Allergie</em>.</p>
<section id="hypothesen-und-signifikanzniveau" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="hypothesen-und-signifikanzniveau"><span class="header-section-number">8.3.1</span> Hypothesen und Signifikanzniveau</h3>
<p><span class="math inline">\(H_0\)</span>: Es besteht keine Beziehung zwischen einer Allergie bei Kindern und deren Eltern. Die relative Häufigkeit der Kinder, bei denen mindestens ein Elternteil eine Allergie hat(te), ist in den Populationen der Allergiker und der Nichtallergiker gleich. Wir nehmen also an: Die Wahrscheinlichkeit, dass mindestens ein Elternteil eine Allergie hatte, hat keinen Zusammenhang damit, ob das befragte Kind selber eine Allergie hat oder nicht.</p>
<p><span class="math inline">\(H_A\)</span>: Es besteht eine Beziehung zwischen einer Allergie bei Kinderen und deren Eltern. Die relative Häufigkeit der Kinder, bei denen mindestens ein Elternteil eine Allergie hatte, unterscheidet sich zwischen den Populationen der Allergiker und der Nichtallergiker. Wir nehmen also an: Die Wahrscheinlichkeit, dass mindestens ein Elternteil eine Allergie hat(te), hängt davon ab, ob die befragte Person selber eine Allergie hat oder nicht.</p>
<p>Als Entscheidungsgrenze legen wir auch in diesem Fall ein Signifikanzniveau von <span class="math inline">\(\alpha = 0.05\)</span> fest.</p>
<p>Für die Darstellung der Ergebnisse eignet sich eine Vierfeldertafel (Kreuztabelle, Kontingenztabelle), welche in <code>R</code> mit dem Befehl <code>table()</code> erstellt werden kann. Absolute Werte können wie folgt tabelliert werden:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Die erste Variable steht in den Zeilen, die zweite in den Spalten</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">table</span>(parsifal<span class="sc">$</span>eltern, parsifal<span class="sc">$</span>kind, <span class="at">dnn =</span> <span class="fu">c</span>(<span class="st">"Eltern"</span>, <span class="st">"Kind"</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>tab</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Kind
Eltern Nein Ja
  Nein   17  7
  Ja      5  9</code></pre>
</div>
</div>
<p>Mit Randhäufigkeiten:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(tab)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Kind
Eltern Nein Ja Sum
  Nein   17  7  24
  Ja      5  9  14
  Sum    22 16  38</code></pre>
</div>
</div>
<ul>
<li>17 Mal haben Eltern und Kinder keine Allergie.</li>
<li>7 Mal hat das Kind eine Allergie, aber die Eltern nicht.</li>
<li>5 Mal haben die Eltern eine Allergie, aber das Kind nicht.</li>
<li>9 Mal haben Eltern und Kinder eine Allergie.</li>
</ul>
<p>Relative Werte können wie folgt tabelliert werden:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">##relative Häufigkeit für gemeinsames Ereignis</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">proportions</span>(tab)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Kind
Eltern      Nein        Ja
  Nein 0.4473684 0.1842105
  Ja   0.1315789 0.2368421</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(<span class="fu">proportions</span>(tab))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Kind
Eltern      Nein        Ja       Sum
  Nein 0.4473684 0.1842105 0.6315789
  Ja   0.1315789 0.2368421 0.3684211
  Sum  0.5789474 0.4210526 1.0000000</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">## relative Häufigkeit für bedingtes Ereignis</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">proportions</span>(tab,<span class="at">margin=</span><span class="dv">1</span>) <span class="co"># gegeben Zeilen, </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Kind
Eltern      Nein        Ja
  Nein 0.7083333 0.2916667
  Ja   0.3571429 0.6428571</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">proportions</span>(tab,<span class="at">margin=</span><span class="dv">2</span>) <span class="co"># gegeben Kolonnen</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Kind
Eltern      Nein        Ja
  Nein 0.7727273 0.4375000
  Ja   0.2272727 0.5625000</code></pre>
</div>
</div>
<p><strong>Wichtig</strong>: Unterscheiden Sie dabei Zeilen und Spaltenprozente!</p>
<ul>
<li>Gegeben die Eltern haben eine Allergie, haben 64% der Kinder auch eine Allergie.</li>
<li>Gegeben die Eltern haben keine Allergie, haben 71% der Kinder auch keine Allergie.</li>
<li>Gegeben das Kind hat eine Allergie, haben 56% der Eltern auch eine Allergie.</li>
<li>Gegeben das Kind hat keine Allergie, haben 77% der Eltern auch keine Allergie.</li>
</ul>
<p>Als nächstes möchten wir erfahren, ob die beobachteten Daten den Erwartungen unter der Nullhypothese entsprechen. Dazu müssen wir die erwarteten Werte berechnen.</p>
</section>
<section id="berechnen-der-erwarteten-werte-unter-der-nullhypothese" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="berechnen-der-erwarteten-werte-unter-der-nullhypothese"><span class="header-section-number">8.3.2</span> Berechnen der erwarteten Werte unter der Nullhypothese</h3>
<p>Unter <span class="math inline">\(H_0\)</span> gilt, dass die beiden Variablen (hier <code>eltern</code> und <code>kind</code>) unabhängig von einander sind. Unabhängig bedeutet, dass die gemeinsame Wahrscheinlichkeit <span class="math inline">\(P(A \cap B)\)</span> (z.B. die Wahrscheinlichkeit, dass ein Kind eine Allergie hat <strong>und</strong> die Eltern die Allergie haben) gerade das Produkt der Randwahrscheinlichkeiten ist:</p>
<p><span class="math display">\[
p_{ij}=p_{i,}\times p_{,j},
\]</span> wobei wir <span class="math inline">\(i\)</span> für Zeilen und <span class="math inline">\(j\)</span> für Spalten verwenden.</p>
<p>Die Wahrscheinlichkeit, dass ein Kind eine Allergie hat <strong>und</strong> die Eltern die Allergie haben (Zelle unten rechts), wenn die Variablen <code>eltern</code> und <code>kind</code> unabhängig sind von einander, ist also <span class="math inline">\(p_{2,2}= 0.37 \times 0.43 = 0.155\)</span>. Wenn wir diese Wahrscheinlichkeit noch mit <span class="math inline">\(n\)</span> multiplizieren (<span class="math inline">\(0.37 \times 0.43 \times 38 = 5.9\)</span>) , erhalten wir die absolute erwartete Häufigkeit unter Unabhängigkeit, also unter <span class="math inline">\(H_0\)</span>. Wenn Sie nun die Werte mit den beobachteten Werten in den Tabellen oben vergleichen, sind diese nicht identisch. Es gibt also eine gewisse Abweichung der beobachteten Werte von den erwarteten Werten. Sind diese Abweichungen stark genug, um <span class="math inline">\(H_0\)</span> zu verwerfen? Mehr dazu später.</p>
<p>Man kann die Formel zur Berechnung der Erwarteten Häufigktien <span class="math inline">\(\hat{E}_{i,j}\)</span> umformen und vereinfachen: Die erwartete Häufigkeit <span class="math inline">\(\hat{E}\)</span> der Zelle <span class="math inline">\(i,j\)</span> erhalten wir, in dem man die Zeilensumme <span class="math inline">\(i\)</span> und die Spaltensumme <span class="math inline">\(j\)</span> multipliziert und durch das Gesamttotal <span class="math inline">\(n\)</span> dividiert.</p>
<p>Schema:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 40%">
<col style="width: 40%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Spalte A</th>
<th>Spalte B</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zeile A</td>
<td><span class="math inline">\(\frac{Zeilensumme A \times Spaltensumme A}{Total}\)</span></td>
<td><span class="math inline">\(\frac{Zeilensumme A \times Spaltensumme B}{Total}\)</span></td>
<td>Zeilensumme A</td>
</tr>
<tr class="even">
<td>Zeile B</td>
<td><span class="math inline">\(\frac{Zeilensumme B \times Spaltensumme A}{Total}\)</span></td>
<td><span class="math inline">\(\frac{Zeilensumme B \times Spaltensumme B}{Total}\)</span></td>
<td>Zeilensumme B</td>
</tr>
<tr class="odd">
<td></td>
<td>Spaltensumme A</td>
<td>Spaltensumme B</td>
<td>Total</td>
</tr>
</tbody>
</table>
<p>Übungshalber kann man das von Hand machen, einfacher geht es aber mit <code>R</code>. Dort werden beim <span class="math inline">\(\chi^2\)</span>-Test die erwarteten Werte mitabgespeichert:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Der Chi-Quadrat Test berechnet die erwarteten Häufigkeiten automatisch</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Mit $expected kann man diese gezielt abrufen. </span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab)<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Kind
Eltern      Nein        Ja
  Nein 13.894737 10.105263
  Ja    8.105263  5.894737</code></pre>
</div>
</div>
<p>Die erwarteten Häufigkeiten sind also die Häufigkeiten, wie man sie unter <span class="math inline">\(H_0\)</span> erwarten würde.</p>
<p>Der Vergleich der erwarteten mit den beobachteten Werten unterstützt unsere bereits gemachte Vermutung: Die beobachteten Fälle, bei denen die Eltern den gleichen Allergiestatus haben wie die Kinder sind etwas grösser, als wir sie unter der Nullhypothese erwarten würden. Die Abweichungen sind aber nicht extrem.</p>
</section>
<section id="voraussetzungen" class="level3" data-number="8.3.3">
<h3 data-number="8.3.3" class="anchored" data-anchor-id="voraussetzungen"><span class="header-section-number">8.3.3</span> Voraussetzungen</h3>
<p>Um einen <span class="math inline">\(\chi^2\)</span>-Test durchzuführen müssen folgende Voraussetzungen erfüllt sein:</p>
<ul>
<li>Die erwarteten Häufigkeiten in jeder Zelle der Tabelle müssen <span class="math inline">\(\ge 5\)</span> sein. Ist diese Bedingung nicht erfüllt, kann der <strong>Fisher’s exakter Test</strong> verwendet werden.</li>
<li>Der Test darf nur auf absolute Häufigkeiten und niemals auf relative Häufigkeiten angewendet werden.</li>
<li>Die Daten stammen aus einer Zufallsstichprobe.</li>
</ul>
</section>
<section id="teststatistik" class="level3" data-number="8.3.4">
<h3 data-number="8.3.4" class="anchored" data-anchor-id="teststatistik"><span class="header-section-number">8.3.4</span> Teststatistik</h3>
<p>Um eine Entscheidung zu treffen, ob der Zusammenhang zwischen den beiden Variablen statistisch signifikant ist, müssen wir die Testgrösse <span class="math inline">\(\chi^2\)</span> berechnen. Die Formel dazu ist:</p>
<p><span class="math display">\[
\chi^2 = \sum_{i=1}^k \sum_{j = 1}^m \frac{(O_{i,j} - \hat{E}_{i,j})^2}{\hat{E}_{i,j}}, i = 1, \dots, k;~j = 1, \dots, m,
\]</span></p>
<p>bei <span class="math inline">\(k\)</span> Zeilen und <span class="math inline">\(m\)</span> Spalten.</p>
<p>Das sieht für manche beängstigend aus, aber wir machen das hier nur, um das Prinzip zu zeigen: <span class="math inline">\(O\)</span> steht für beobachtete Werte, <span class="math inline">\(\hat{E}\)</span> für erwartete Werte. Jetzt setzen wir unsere Werte aus der Tabelle oben in die Formel ein:</p>
<p><span class="math display">\[\chi^2 = \frac{(17-13.9)^2}{13.9} + \frac{(5-8.1)^2}{8.1} + \frac{(7-10.1)^2}{10.1} + \frac{(9-5.9)^2}{5.9} \approx 4.46\]</span></p>
<p>Unsere Teststatistik ist <span class="math inline">\(\chi^2 = 4.46\)</span>. Wie für die für Sie bereits bekannten Teststatistiken <span class="math inline">\(Z\)</span> und <span class="math inline">\(T\)</span> oder <span class="math inline">\(F\)</span> existiert auch für <span class="math inline">\(\chi^2\)</span> eine spezifische Wahrscheinlichkeitsdichtefunktion. Es würde zu weit führen, im Detail auf diese Verteilung einzugehen, deren Form wie bei der <span class="math inline">\(t\)</span>-Verteilung nur durch die Anzahl Freiheitsgrade <span class="math inline">\(df\)</span> definiert ist. Anhand von Tabellen oder mit <code>R</code> ist es möglich, die Wahrscheinlichkeit für unseren <span class="math inline">\(\chi^2\)</span>-Wert oder einen extremeren zu berechnen. In <code>R</code> erfolgt diese Berechnung mit der Funktion <code>pchisq()</code>. Die Freiheitsgrade in einer <span class="math inline">\(k \times m\)</span>-Tabelle werden berechnet als <span class="math inline">\(df = (k - 1)\times(m-1)\)</span>, im vorliegenden Fall also: <span class="math inline">\(df = (2-1)\times(2-1) = 1\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="fl">4.46</span>, <span class="at">df =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0346975</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-x2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-x2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08_inf_cat_data_files/figure-html/fig-plot-x2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-x2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;8.1: Chi-Quadrat-Verteilung für df = 1
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ohne komplizierte Berechnungen kann der Test in <code>R</code> durchgeführt werden:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Durchführung des Chi-Quadrat Tests in R ohne Korrektur</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tab
X-squared = 4.4737, df = 1, p-value = 0.03442</code></pre>
</div>
</div>
<p>Da die Voraussetzungen bzgl. den Zellhäufigkeiten nur knapp erfüllt sind, wird hier noch Fisher’s exakter Test gezeigt.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Durchführung des Fisher’s exact Test </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(tab)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  tab
p-value = 0.04684
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
  0.8852972 22.6151747
sample estimates:
odds ratio 
   4.18771 </code></pre>
</div>
</div>
</section>
<section id="interpretation-des-chi2-tests" class="level3" data-number="8.3.5">
<h3 data-number="8.3.5" class="anchored" data-anchor-id="interpretation-des-chi2-tests"><span class="header-section-number">8.3.5</span> Interpretation des <span class="math inline">\(\chi^2\)</span>-Tests</h3>
<p>Die Wahrscheinlichkeit für <span class="math inline">\(\chi^2 &gt; 4.47\)</span> und <span class="math inline">\(df = 1\)</span> ist <span class="math inline">\(p = 0.034\)</span>. Da der P-Wert kleiner als das Signifikanzniveau <span class="math inline">\(\alpha = 0.05\)</span> ist, verwerfen wir die Nullhypothese zu Gunsten der Alternativhypothese.</p>
<p>Im <code>R</code> Code habe ich aus didaktischen Gründen eine Korrektur ausgeschaltet, damit Sie sehen, dass die manuelle Berechnung und die Berechnung mit R übereinstimmten. Per default wird diese Korrektur durchgeführt und es empfiehlt sich, die Korrektur nicht manuell zu unterdrücken. Wenn wir den Test nochmals, dieses Mal mit Korrektur durchführen, erhalten wir folgendes Resultat:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Durchführung des Chi-Quadrat Tests in R mit Korrektur</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  tab
X-squared = 3.149, df = 1, p-value = 0.07597</code></pre>
</div>
</div>
<p>Nun ist der P-Wert knapp über der Grenze von 5% und wir ziehen deshalb folgende Schlussfolgerung: Untersucht wurde die Frage, ob eine Beziehung zwischen dem Allergiestatus von Kindern und dem Allergiestatus ihrer Eltern besteht. Anhand einer Zufallsstichprobe von 38 Kindern und deren Eltern konnte kein statistisch signifikanter Zusammenhang festgestellt werden: <span class="math inline">\(\chi^2\)</span> Statistik = 3.149, p = 0.076. Beachten Sie, dass mit Fisher’s exaktem Test diese Interpretation anders ausfallen würde (siehe oben), obwohl sich der P-Wert selber nur minimal verändert. Dieses Beispiel zeigt die Problematik einer willkürlichen Dichotomisierung des P-Werts deutlich auf.</p>
</section>
<section id="chi2-test-bei-variablen-mit-mehr-als-zwei-ausprägungen" class="level3" data-number="8.3.6">
<h3 data-number="8.3.6" class="anchored" data-anchor-id="chi2-test-bei-variablen-mit-mehr-als-zwei-ausprägungen"><span class="header-section-number">8.3.6</span> <span class="math inline">\(\chi^2\)</span>-Test bei Variablen mit mehr als zwei Ausprägungen</h3>
<p>Solange die Voraussetzungen erfüllt sind, kann der <span class="math inline">\(\chi^2\)</span>-Test auch durchgeführt werden, wenn die beiden Variablen mehr als zwei Ausprägungen haben. Durchführung und Interpretation sind analog zum Beispiel oben.</p>
</section>
</section>
<section id="sec-proportionen" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="sec-proportionen"><span class="header-section-number">8.4</span> Proportionen</h2>
<p>Es kommt oft vor, dass man auf Grundlage einer Stichprobe eine <strong>Proportion</strong> <span class="math inline">\(\pi\)</span> schätzen möchte. Zuerst wird gezeigt, wie man den Standardfehler für eine Proportion oder eine Proportionsdifferenz mit Hilfe der Normalapproximation der Binomialverteilung berechnen kann. Man kann nämlich zeigen, dass die Verteilung von Stichprobenproportionen einer Normalverteilung folgt, wenn <span class="math inline">\(n\)</span> gross ist (= zentraler Grenzwertsatz). Nehmen wir an, wir wollen wissen, welche Proportion von Studierenden in Gesundheitsberufen im Verlaufe der Karriere einen MSc an einen BSc hängt. Dazu wird ein Umfrage gemacht. Wir simulieren die Daten je 1000 mal für vier Stichprobengrössen: <span class="math inline">\(n = 3\)</span>, <span class="math inline">\(n = 5\)</span>, <span class="math inline">\(n = 10\)</span> und <span class="math inline">\(n = 30\)</span>. Wir nehmen an, dass die wahre Proportion <span class="math inline">\(\pi = 0.2\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-prop-n" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-prop-n-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08_inf_cat_data_files/figure-html/fig-plot-prop-n-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-prop-n-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;8.2: Verteilung von Proportionen mit verschiedenen Stichprobengrössen. Der Rote Strich repräsentiert die wahre Proportion.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="berechnungen-von-hand" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="berechnungen-von-hand"><span class="header-section-number">8.4.1</span> Berechnungen von Hand</h3>
<p>Man sieht in <a href="#fig-plot-prop-n" class="quarto-xref">Abbildung&nbsp;<span>8.2</span></a>, dass sich die Verteilung der Stichprobenproportionen mit steigendem <span class="math inline">\(n\)</span> immer mehr einer Normalverteilung annähert (= zentraler Grenzwertsatz). Für grosse Stichproben kann der Standardfehler wie folgt berechnet werden:</p>
<p><span class="math display">\[
SE_{\hat{\pi}} = \sqrt{\frac{\hat{\pi}(1-\hat{\pi})}{n}},
\]</span></p>
<p>wobei <span class="math inline">\(\hat\pi\)</span> die Stichprobenproportion ist.</p>
<p>Für eine Stichprobe mit <span class="math inline">\(n = 80\)</span> und <span class="math inline">\(\hat{\pi} = 0.2\)</span> gilt somit <span class="math inline">\(SE_{\hat{\pi}} = 0.0447\)</span>. Damit kann man ein approximatives Konfidenzintervall berechnen:</p>
<p><span class="math display">\[
CI_{1-\alpha} = \hat{\pi}\pm z_{1-\alpha/2} SE_{\hat{\pi}}
\]</span></p>
<p>Das 95% Konfidenzintervall für das obige Beispiel ist demnach <span class="math inline">\(0.2 \pm 1.96 * 0.0447 = [0.112; 0.288]\)</span>.</p>
<p>Mit <code>R</code></p>
<p>Der Standardfehler für eine <strong>Proportionsdifferenz</strong> (meistens von zwei Gruppen) kann mit Hilfe der Varianz-Regel berechnet werden:</p>
<p><span class="math display">\[
SE_{\hat{\pi_1}-\hat{\pi_2}} = \sqrt{SE_{\hat{\pi_1}}^2 + SE_{\hat{\pi_2}}^2}
\]</span></p>
<p><strong>Beispiel:</strong> In einer Studie sterben in der Interventionsgruppe 20 der insgesamt 150 Personen (<span class="math inline">\(\hat\pi_{I} =13.3\%\)</span>), in der Placebogruppe 31 von 150 (<span class="math inline">\(\hat\pi_{C} =20.7\%\)</span>). Wir kürzen zur Übersicht die Interventionsgruppe mit <em>I</em> und die Placebogruppe mit <em>C</em> ab. Zuerst wird der Standardfehler für jede Gruppe berechnet: <span class="math inline">\(SE_{\hat{\pi_{I}}} = 0.0277\)</span>, <span class="math inline">\(SE_{\hat{\pi_{C}}} = 0.033\)</span>. Danach kann der Standardfehler für die Proportionsdifferenz <span class="math inline">\(|\hat{\pi_{I}}-\hat{\pi_{C}}| = 0.074\)</span> berechnet werden: <span class="math inline">\(SE_{\hat{\pi_{I}}-\hat{\pi_{C}}} = 0.0431\)</span>. Damit kann wiederum ein Konfidenzintervall berechnet werden:</p>
<p><span class="math display">\[
I_{0.95} = 0.074 \pm 1.96 * 0.0431 = [-0.01; 0.158]
\]</span></p>
<p>Man sieht dem Intervall an, dass sich die beiden Proportionen nicht statistisch signifikant unterscheiden (bei <span class="math inline">\(\alpha = 0.05\)</span>). In dem man die geschätzte Grösse (in diesem Fall <span class="math inline">\(|\hat{\pi_{I}}-\hat{\pi_{C}}| = 0.074\)</span>) durch deren Standardfehler dividiert, erhält man einen <span class="math inline">\(z\)</span>-Wert:</p>
<p><span class="math display">\[
z = \frac{|\hat{\pi_{I}}-\hat{\pi_{C}}|}{SE_{\hat{\pi_{I}}-\hat{\pi_{C}}}} = \frac{0.074}{0.0431} = 1.717
\]</span></p>
<p>Mit dem z-Wert kann man einen zweiseitigen P-Wert berechnen:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(<span class="fl">1.717</span>))<span class="sc">*</span><span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08597917</code></pre>
</div>
</div>
<p>Anmerkung: Diese manuelle Berechnung stützt sich auf die Approximation der Normalverteilung (darum resultiert ein Z-Wert) und ist daher nur bei grossen Stichproben genau. Die Berechnung ist aber eine andere als mit der <code>R</code>-Funktion <code>prop.test()</code> (siehe nächstes unten). Letztere ist genauer.</p>
</section>
<section id="sec-berechnungen-von-proportionen-mit-r" class="level3" data-number="8.4.2">
<h3 data-number="8.4.2" class="anchored" data-anchor-id="sec-berechnungen-von-proportionen-mit-r"><span class="header-section-number">8.4.2</span> Berechnungen von Proportionen mit <code>R</code></h3>
<p>Natürlich gibt es implementierte <code>R</code> Funktionen, welche einem die Rechnerei abnehmen. Für Proportionen eignet sich die Funktion <code>prop.test()</code>. Hier werden die Beispiele von oben wiederholt, damit sie die Unterschiede sehen können.</p>
<p>In <code>R</code> berechnet man für eine Stichprobe mit <span class="math inline">\(n = 80\)</span> und <span class="math inline">\(\hat{\pi} = 0.2\)</span> das 95% Konfidenzinterall wie folgt:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Durchführung eines Proportionstests für eine Stichprobe</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">80</span><span class="sc">*</span><span class="fl">0.2</span>, <span class="dv">80</span>) <span class="co"># Die Erste Zahl ist die Anzahl Ereignisse, die zweite das n</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test with continuity correction

data:  80 * 0.2 out of 80, null probability 0.5
X-squared = 27.613, df = 1, p-value = 1.482e-07
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
 0.1220253 0.3073565
sample estimates:
  p 
0.2 </code></pre>
</div>
</div>
<p>Sie sehen, dass hier für die Berechnung des P-Wertes die <span class="math inline">\(\chi^2\)</span>-Statistik verwendet wird, die Sie bereits oben kennengelernt haben. In diesem Test ist <span class="math inline">\(H_0: \pi = 0.5\)</span> (siehe Output). Dieser Nullwert ist standardmässig so hinterlegt, kann aber bei Bedarf geändert werden. Der P-Wert bezieht sich folglich darauf, ob sich <span class="math inline">\(\hat{\pi}\)</span> signifikant von 0.5 unterscheidet. Dies ist äquivalent zu einen Einstrichproben T-Test mit einem definierten Nullwert. Oft interessiert man sich bei Proportionen nicht für einen Vergleich mit einem Nullwert, sondern lediglich für ein Konfidenzintervall (so auch in diesem Fall). Das 95% Konfidenzintervall sehen wir weiter unten im Output. Es ist sehr ähnlich, aber nicht ganz identisch wie das von Hand Berechnete. Zuunterst wird nochmals die Stichprobenproportion ausgegeben.</p>
<p>Die Funktion <code>prop.test()</code> eignet sich ebenfalls für den Vergleich der Proportionen von zwei Stichproben. Wir greifen dazu noch einmal das Beispiel von oben auf: In einer Studie sterben in der Interventionsgruppe 20 von 150 (13.3%) Personen, in der Placebogruppe 31 von 150 (20.7%). Unterscheiden sich die Proportionen in den beiden Gruppen?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Durchführung eine Proportionstests für zwei Stichproben</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="fu">c</span>(<span class="dv">31</span>, <span class="dv">20</span>), <span class="fu">c</span>(<span class="dv">150</span>,<span class="dv">150</span>)) <span class="co"># Der erste Vektor umfasst die Anzahl Ereignisse pro Gruppe, der zweite Vektor das n pro Gruppe</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  c(31, 20) out of c(150, 150)
X-squared = 2.3624, df = 1, p-value = 0.1243
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.0179395  0.1646062
sample estimates:
   prop 1    prop 2 
0.2066667 0.1333333 </code></pre>
</div>
</div>
<p><br>
Der Output sieht ähnlich aus, wie beim Einstichproben Proportionstest. Ganz unten sehen wir die beiden Stichprobenproportionen. Darüber wird das 95% Konfidenzintervall für die Proportionsdifferenz ausgegeben. Weil dieses die <em>Null</em> schneidet, wissen wir bereits, dass der zweiseitige P-Wert über 5% liegen muss. Dieser beträgt 12.43%. Es liegt also keine Evidenz dafür vor, dass sich die beiden Proportionen unterscheiden, <span class="math inline">\(H_0\)</span> wird beibehalten. Auch hier wird die <span class="math inline">\(\chi^2\)</span>-Statistik für die Berechnung des P-Wertes verwendet. Tatsächlich kann man in dieser Situation auch eine Vierfeldertabelle zeichnen:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>              Died
Group           No Yes
  Intervention 130  20
  Placebo      119  31</code></pre>
</div>
</div>
<p>Diese kann anschliessend mit einem <span class="math inline">\(\chi^2\)</span>-Test ausgewertet werden:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  tab
X-squared = 2.3624, df = 1, p-value = 0.1243</code></pre>
</div>
</div>
<p>Wie Sie sehen, kommt der <span class="math inline">\(\chi^2\)</span>-Test zum genau gleichen Ergebnis wie der Proportionstest (hoffentlich!). Der Output von <code>prop.test()</code> ist aber informativer: Anstatt nur eines P-Wertes können wir die Proportionen direkt vergleichen und erhalten zudem ein 95% Konfidenzintervall für die Proportionsdifferenz. In Situationen wo Proportionen sinnvoll sind, ist also der Proportionstest dem <span class="math inline">\(\chi^2\)</span>-Test vorzuziehen. Dies gilt auch für das Beispiel ganz oben in <a href="09_logistic_regression.html#sec-der-chi2-test" class="quarto-xref"><span>Section 9.3</span></a> mit den Allergien.</p>
</section>
</section>
<section id="risiken" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="risiken"><span class="header-section-number">8.5</span> Risiken</h2>
<p>Hier wird weiter das fiktive Beispiel von oben verwendet: In einer Studie sterben in der Interventionsgruppe 20 von 150 (13.3%) Personen, in der Placebogruppe 31 von 150 (20.7%). Zur Übersicht noch einmal die Vierfeldertabelle:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>              Died
Group           No Yes
  Intervention 130  20
  Placebo      119  31</code></pre>
</div>
</div>
<p>Angenommen wir wissen, dass die Beobachtungszeit in dieser Studie für alle Teilnehmenden exakt gleich war, sagen wir ein Jahr. Dann ist die Proportion der Personen, welche in der jeweiligen Gruppe sterben auch das <strong>Risiko,</strong> bzw. die Wahrscheinlichkeit in einem Jahr zu sterben:</p>
<ul>
<li>Das Risiko, in der Interventionsgruppe innerhalb eines Jahres zu sterben ist:</li>
</ul>
<p><span class="math display">\[
\widehat{Risk_{I}} = \frac{\#Ereignisse_{I}}{n_{I}} = \frac{20}{150} = 0.133
\]</span></p>
<ul>
<li>Das Risiko, in der Placebogruppe innerhalb eines Jahres zu sterben ist</li>
</ul>
<p><span class="math display">\[
\widehat{Risk_{C}} = \frac{\#Ereignisse_{C}}{n_{C}} = \frac{31}{150} = 0.207
\]</span></p>
<section id="berechnungen-von-hand-1" class="level3" data-number="8.5.1">
<h3 data-number="8.5.1" class="anchored" data-anchor-id="berechnungen-von-hand-1"><span class="header-section-number">8.5.1</span> Berechnungen von Hand</h3>
<p>Wie Sie sehen, lassen sich Risiken einfach anhand von Vierfeldtabellen berechnen. Häufig setzt man in Studien die Risiken von zwei Gruppen ins Verhältnis zu einander. Diese Effektgrösse wird in Studien <strong><em>Risk Ratio</em></strong> oder <strong><em>Relative Risk</em></strong>, kurz RR genannt und wie folgt berechnet:</p>
<p><span class="math display">\[
\widehat{RR} = \frac{\widehat{Risk_{I}}}{\widehat{Risk_{C}}} = \frac{0.133}{0.207} = 0.643
\]</span></p>
<p>folglich gilt:</p>
<p><span class="math display">\[
\widehat{Risk_{I}} = \widehat{Risk_{C}} * \widehat{RR} = 0.207 * 0.643 = 0.133
\]</span></p>
<p><strong>Interpretation eines RR</strong></p>
<ul>
<li><p>RR &lt; 1 bedeutet, dass das Risiko für ein Ereignis in der Interventionsgruppe tiefer ist.</p></li>
<li><p>RR &gt; 1 bedeutet, dass das Risiko für ein Ereignis in der Kontrollgruppe tiefer ist.</p></li>
<li><p>RR = 1 bedeutet, dass das Risiko für ein Ereignis in beiden Gruppen gleich ist.</p></li>
</ul>
<p><strong>Wichtig:</strong> Ein Ereignis muss nicht zwingend mit einem negativen Gesundheitszustand in Verbindung gebracht werden. Man könnte auch das Überleben als Ereignis nehmen, folglich wäre ein RR &gt; 1 wünschenswert.</p>
<p>Das in diesem Fall berechnete RR kann folgendermassen interpretiert werden: Das Risiko, innerhalb eines Jahres zu sterben entspricht in der Interventionsgruppe nur 64.3% desjenigen in der Placebogruppe. Oder anders: In der Interventionsgruppe ist das relative Risiko, innerhalb eines Jahres zu sterben <span class="math inline">\(1-0.643 = 0.357 = 35.7\%\)</span> tiefer. Diese 35.7% werden manchmal als <em>Relative Risk Reduction,</em> kurz RRR bezeichnet.</p>
<p><span class="math display">\[
\widehat{RRR} = \widehat{RR} -1= 0.643-1 = -0.357
\]</span></p>
<p>Falls ein RR &gt; 1, dann entspricht RRR der relativen Risikozunahme. Angenommen RR = 2.34. Dann ist das relative Risiko in der Interventionsgruppe 134% höher.</p>
<p>Die absolute Risikodifferenz, auch <strong><em>Risk Difference</em></strong>, RD berechnet sich wie folgt:</p>
<p><span class="math display">\[
\widehat{RD} = \widehat{Risk_{I}} - \widehat{Risk_{C}} = 0.133 - 0.207 = -0.074
\]</span></p>
<p>Absolut gesehen ist das Risiko in der Interventionsgruppe 7.4% tiefer. Wenn die RD zugunsten der Intervention ist, kann anhand der RD die sogenannte <strong><em>Number needed to treat</em></strong>, NNT berechnet werden. Sie sagt aus, wie viele Personen behandelt werden müssen, damit ein Ereignis verhindert werden kann:</p>
<p><span class="math display">\[
\widehat{NNT} = \frac{1}{|\widehat{RD}|} = \frac{1}{0.074} = 13.5 \approx 14
\]</span></p>
<section id="sec-standardfehler-von-risk-ratios" class="level4" data-number="8.5.1.1">
<h4 data-number="8.5.1.1" class="anchored" data-anchor-id="sec-standardfehler-von-risk-ratios"><span class="header-section-number">8.5.1.1</span> Standardfehler von Risk Ratios</h4>
<p>Bei einem RR ist 1 die eigentliche Mitte (beide Risiken sind gleich gross). Ist das Risiko in der Interventionsgruppe tiefer, nimmt das RR einen Wert zwischen 0 und 1 an. Ist es grösser, zwischen 1 und <span class="math inline">\(\infty\)</span>. Offensichtlich ist der Weg von 0 bis 1 viel kürzer als von 1 bis <span class="math inline">\(\infty\)</span>. Aus diesem Grund sind RR typischerweise rechtsschief verteilt. Die Normalverteilung eignet sich also nicht gut für die Modellierung von RR. Es gibt jedoch einen Trick: Wenn man RR logarithmiert, dann ist deren Verteilung normal! Solche Log-Transformationen kommen häufig vor.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-rr-log-dist" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-rr-log-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08_inf_cat_data_files/figure-html/fig-plot-rr-log-dist-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-rr-log-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;8.3: Simulation von RR verschiedener Stichprobengrössen. Das wahre RR beträgt 3
</figcaption>
</figure>
</div>
</div>
</div>
<p>Man berechnet Standardfehler, P-Werte und die Grenzen eines Konfidenzintervalls für das logarithmierte RR (für welche die Normalvertilung ein adäquates Modell ist) und exponiert danach das RR und die Grenzen des Konfidenzintervalls wieder.</p>
<p>Hinweis: wenn wir in diesem Kurs vom Logarithmus reden, dann ist immer der natürliche Logarithmus gemeint, also jener mit der Eulerschen Zahl als Basis.</p>
<p>Aus <a href="#sec-proportionen" class="quarto-xref"><span>Section 8.4</span></a> wissen wir, dass für eine Proportion, bzw. in diesem Fall für ein Risiko gilt:</p>
<p><span class="math display">\[
SE_{\hat{\pi}} = \sqrt{\frac{\hat{\pi}(1-\hat{\pi})}{n}}
\]</span></p>
<p>wobei</p>
<p><span class="math display">\[
\hat{\pi} = \frac{\#Ereignisse}{n}.
\]</span></p>
<p>Es wäre nun praktisch, wenn man für ein Verhältnis von Risiken (= RR) analog vorgehen könnte, wie bei Differenzen von Proportionen, bzw. Mittelwerten, um den Standardfehler dieser Differenz zu berechnen:</p>
<p><span class="math display">\[
SE_{Quant_{I}-Quant_{C}} = \sqrt{SE_{Quant_{I}}^2 + SE_{Quant_{C}}^2}.
\]</span></p>
<p>Im Falle von RR geht es aber nicht um Differenzen, sondern um Verhältnisse, weshalb gilt:</p>
<p><span class="math display">\[
SE_{RR} \ne \sqrt{SE_{Risk_{I}}^2 + SE_{Risk_{C}}^2}.
\]</span></p>
<p>Wenn wir aber den Standardfehler des <span class="math inline">\(log(RR)\)</span> berechnen, profitieren wir von folgender Regel der Logarithmen, mit der man wieder auf additiver Skala arbeiten kann:</p>
<p><span class="math display">\[
log(RR) = log(Risk_{I}) - log(Risk_{C})
\]</span></p>
<p>Aus diesem Grund können wir den Standardfehler des <span class="math inline">\(log(\widehat{RR})\)</span> wie folgt berechnen:</p>
<p><span class="math display">\[
se_{log(\widehat{RR})} = \sqrt{se_{log(\widehat{Risk_{I}})}^2 + se_{log(\widehat{Risk_{C}})}^2}.
\]</span></p>
<p>Man kann nun zeigen, dass obige Gleichung äquivalent ist mit</p>
<p><span class="math display">\[
se_{log(\widehat{RR})} = \sqrt{\frac{1}{\#Ereignisse_{I}}-\frac{1}{n_{I}}+\frac{1}{\#Ereignisse_{C}}-\frac{1}{n_{C}}}.
\]</span></p>
<p>Wenden wir diese Formeln auf unser Beispiel an, so erhalten wir:</p>
<p><span class="math display">\[
log(\widehat{RR}) = log(0.643) = -0.442,
\]</span></p>
<p><span class="math display">\[
se_{log(\widehat{RR})} = \sqrt{\frac{1}{\#Ereignisse_{I}}-\frac{1}{n_{I}}+\frac{1}{\#Ereignisse_{C}}-\frac{1}{n_{C}}},
\]</span></p>
<p><span class="math display">\[
= \sqrt{\frac{1}{20} - \frac{1}{150} + \frac{1}{31} - \frac{1}{150}} = 0.263.
\]</span></p>
<p>Damit können wir ein 95% Konfidenzintervall für das <span class="math inline">\(log(RR)\)</span> berechnen:</p>
<p><span class="math display">\[
I_{0.95_{log(RR)}} = log(\widehat{RR}) \pm 1.96 * se_{log(\widehat{RR})} = -0.442 \pm 1.96 * 0.263 = [-0.957; 0.073].
\]</span></p>
<p>Wenn wir die Grenzen dieses Intervalls exponieren erhalten wir <span class="math inline">\([0.384; 1.076]\)</span>.</p>
<p>Wir können also zu 95% darauf vertrauen, dass das wahre RR im Intervall <span class="math inline">\([0.384; 1.076]\)</span> liegt. Weil dieses Intervall den Nullwert <span class="math inline">\(RR = 1\)</span> enthält, unterscheidet sich dieses nicht statistisch signifikant (bei <span class="math inline">\(\alpha = 0.05\)</span>) von 1. Dieses Resultat ist konsistent zu den Berechnungen mit Proportionen.</p>
<p>Zuletzt lässt sich für das RR auch ein P-Wert berechnen:</p>
<p><span class="math display">\[
z = \frac{log(\widehat{RR})}{SE_{log(\widehat{RR})}} = \frac{-0.442}{0.263} = -1.68.
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">1.68</span>) <span class="sc">*</span> <span class="dv">2</span> <span class="co"># * 2 da zweiseitiger P-Wert</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09295732</code></pre>
</div>
</div>
<p>Auch dieser stimmt mit den Berechnungen mit den Proportionen überein.</p>
</section>
</section>
<section id="sec-berechnungen-von-rr-mit-r" class="level3" data-number="8.5.2">
<h3 data-number="8.5.2" class="anchored" data-anchor-id="sec-berechnungen-von-rr-mit-r"><span class="header-section-number">8.5.2</span> Berechnungen von RR mit <code>R</code></h3>
<p>Wenn Sie bist jetzt mit <code>R</code> gekämpft haben, dann sind Sie wahrscheinlich spätestens jetzt froh darum. In diesem Abschnitt wird Ihnen gezeigt, wie Sie Risiken, Risk Ratios, sowie P-Werte und Konfidenzintervalle für Risk Ratios mit <code>R</code> berechnen können. Es existieren zahlreiche <code>R</code>-Pakete zu diesem Zweck. In diesem Modul verwenden wir das Paket <code>epitools</code>. Dieses Paket muss zuerst mit <code>library(epitools)</code> geladen werden, damit auf die entsprechenden Funktionen zugegriffen werden kann.</p>
<p>Als Grundlage für die Berechnungen dient die bekannte Vierfeldertabelle:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>              Died
Group           No Yes
  Intervention 130  20
  Placebo      119  31</code></pre>
</div>
</div>
<p>Für die Berechung in <code>R</code> ist es wichtig, dass die Tabelle im richtigen Format vorliegt. Im Hilfemenü der Funktion <code>riskratio()</code>, welches Sie mit <code>?riskratio</code> abrufen können, finden Sie folgende Angaben zum Format der Tabelle:</p>
<p>If you are providing a 2x2 table the following table is preferred:</p>
<pre><code>                    disease=0   disease=1
    exposed=0 (ref)    n00         n01
    exposed=1          n10         n11  </code></pre>
<p>Wenn man also die Interventionsgruppe, in diesem Fall <em>exposed</em> jeweils mit 1 codiert und die Placebogruppe mit 0, sowie ein Ereignis mit 1 und kein Ereignis mit 0, dann stimmt das Format der Tabelle automatisch. In unserem Fall sind aber die Zeilen verkehrt. Dies kann man mit dem Zusatz <code>rev = "rows"</code> korrigieren. Analog funktioniert auch <code>rev = "colums"</code> oder <code>rev = "both"</code>.</p>
<p>Die Berechnung erfolgt für unser Beispiel also wie folgt:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># laden des Pakets epitools</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epitools)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Berechnung RR, 95% CI und P-Wert</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">riskratio</span>(tab, <span class="at">rev =</span> <span class="st">"rows"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$data
              Died
Group           No Yes Total
  Placebo      119  31   150
  Intervention 130  20   150
  Total        249  51   300

$measure
              risk ratio with 95% C.I.
Group           estimate     lower    upper
  Placebo      1.0000000        NA       NA
  Intervention 0.6451613 0.3856541 1.079291

$p.value
              two-sided
Group          midp.exact fisher.exact chi.square
  Placebo              NA           NA         NA
  Intervention 0.09405295    0.1237165 0.09089263

$correction
[1] FALSE

attr(,"method")
[1] "Unconditional MLE &amp; normal approximation (Wald) CI"</code></pre>
</div>
</div>
<p>Sie sehen unter <code>$data</code>, dass die Tabelle erfolgreich in das richtige Format transformiert wurde. Unter <code>$measure</code> interessiert uns nur die zweite Zeile. Sie sehen, dass das RR sowie dessen 95% Konfidenzintervall bis auf kleine Differenzen mit den Berechnungen von Hand übereinstimmen (die Berechnungsmethode ist allerdings eine andere, siehe <code>attr(,"method")</code>). Unter <code>$p.value</code> wird der P-Wert für das RR mit drei verschiedenen Methoden berechnet. Interpretieren Sie den P-Wert unter <code>chi.square</code>, diesen kennen Sie schon vom <span class="math inline">\(\chi^2\)</span>-Test, bzw. vom Proportionstest. Denken Sie daran, dass bei RR gilt: <span class="math inline">\(H_0: RR = 1\)</span>. Die <em>Yate’s continuity correction</em> wird beim Proportionstest standardmässig durchgeführt, hier aber nicht (siehe <code>$correction</code>). Das ist etwas unglücklich, man kann dies aber mit dem zusätzlichen Argument <code>correction = TRUE</code> ändern.</p>
</section>
</section>
<section id="odds" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="odds"><span class="header-section-number">8.6</span> Odds</h2>
<p>Oft werden in Studien statt Risiken <strong>Odds</strong> berechnet. Einerseits, weil in gewissen Situationen nicht von Risiken gesprochen werden kann (insbesondere bei Fall-Kontrollstudien), andererseits kann man mit Odds besser rechnen als mit Risiken. Aber was sind Odds? Am besten lassen sich Odds mit <em>Chance</em> übersetzen. Wenn wir umganssprachlich sagen, die Chance für ein Ereignis ist <em>fifty-fifty</em>, dann denken wir oft “<em>die Wahrscheinlichkeit für das Ereignis ist 50%</em>”. Das heisst nichts weiteres, als dass die Chance, dass das Ereignis eintrifft, gleich gross ist, wie dass es nicht eintrifft. Die Odds sind also <span class="math inline">\(\frac{50}{50}=1\)</span>. Daraus ergibt sich, dass man eine Wahrscheinlichkeit <span class="math inline">\(P\)</span> wie folgt in Odds umrechnet und umgekehrt:</p>
<p><span class="math display">\[
Odds = \frac{P}{1-P}
\]</span></p>
<p><span class="math display">\[
P = \frac{Odds}{1+Odds}
\]</span></p>
<p>Sie können dies mit dem Beispiel “<em>die Chance ist fifty-fifty</em>” nachrechnen und werden merken, dass die Formeln stimmen. Die Umrechnung von Odds in Wahrscheinlichkeiten und umgekehrt kommt in der Praxis häufig vor. Beachten Sie, dass wir im Beispiel mit der Interventions- (I) und der Placebogruppe (C) angenommen haben, dass der Beobachtungszeitraum für alle Personen gleich ist (ein Jahr). Darum gilt in diesem Fall <span class="math inline">\(Proportion = Risiko = Wahrscheinlichkeit\)</span> für ein Ereignis in einem Jahr.</p>
<section id="berechnung-von-hand" class="level3" data-number="8.6.1">
<h3 data-number="8.6.1" class="anchored" data-anchor-id="berechnung-von-hand"><span class="header-section-number">8.6.1</span> Berechnung von Hand</h3>
<p>Odds lassen sich wie Risiken einfach anhand der Vierfeldertabelle berechnen:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>              Died
Group           No Yes
  Intervention 130  20
  Placebo      119  31</code></pre>
</div>
</div>
<p><span class="math display">\[
\widehat{Odds_{I}} = \frac{\#Ereignisse_{I}}{\#KeineEreignisse_{I}} = \frac{20}{130} = 0.154
\]</span></p>
<p><span class="math display">\[
\widehat{Odds_{C}} = \frac{\#Ereignisse_{C}}{\#KeineEreignisse_{C}} = \frac{31}{119} = 0.261
\]</span></p>
<p>Wenn Sie wollen, können Sie als Übung diese Odds mit den Formeln oben wieder in Wahrscheinlichkeiten, bzw. Proportionen, bzw. Risiken umrechnen.</p>
<p>Wie die Risiken setzt man in Studien die Odds von zwei Gruppen ins Verhältnis zu einander. Diese Effektgrösse wird <strong><em>Odds Ratio</em></strong>, kurz OR genannt und wie folgt berechnet:</p>
<p><span class="math display">\[
\widehat{OR} = \frac{\widehat{Odds_{I}}}{\widehat{Odds_{C}}} = \frac{0.154}{0.261} = 0.59
\]</span></p>
<p>Folglich gilt:</p>
<p><span class="math display">\[
\widehat{Odds_{I}} = \widehat{Odds_{C}} * \widehat{OR} = 0.261 * 0.59 = 0.154
\]</span></p>
<p><strong>Interpretation des OR</strong></p>
<ul>
<li><p>OR &lt; 1 bedeutet, dass die Odds für ein Ereignis in der Interventionsgruppe tiefer sind.</p></li>
<li><p>OR &gt; 1 bedeutet, dass die Odds für ein Ereignis in der Kontrollgruppe tiefer sind.</p></li>
<li><p>OR = 1 bedeutet, dass die Odds für ein Ereignis in beiden Gruppen gleich sind.</p></li>
</ul>
<p><strong>Wichtig:</strong> Ein Ereignis muss nicht zwingend mit einem negativen Gesundheitszustand in Verbindung gebracht werden. Man könnte auch das Überleben als Ereignis nehmen, folglich wäre ein OR &gt; 1 wünschenswert.</p>
<section id="standardfehler-von-odds-ratios" class="level4" data-number="8.6.1.1">
<h4 data-number="8.6.1.1" class="anchored" data-anchor-id="standardfehler-von-odds-ratios"><span class="header-section-number">8.6.1.1</span> Standardfehler von Odds Ratios</h4>
<p>Wie RR sind auch OR rechtsschief verteilt. Aus diesem Grund berechnet man die Schranken eines Konfidenzintervalls sowie P-Werte für das <span class="math inline">\(log(OR)\)</span> und exponiert die Werte anschliessend wieder. Der Standardfehler für das <span class="math inline">\(log(OR)\)</span> berechnet man mit der Formel:</p>
<p><span class="math display">\[
SE_{log(OR)} = \sqrt{\frac{1}{\#Ereignisse_{I}}+\frac{1}{n_{I}-\#Ereignisse_{I}}+\frac{1}{\#Ereignisse_{C}}+\frac{1}{n_{C}-\#Ereignisse_{C}}}
\]</span></p>
<p>Die Formel beruht auf den gleichen Begründungen wie für RR, siehe <a href="#sec-standardfehler-von-risk-ratios" class="quarto-xref"><span>Section 8.5.1.1</span></a>. Angewendet auf unser Beispiel ergibt sich:</p>
<p><span class="math display">\[
log(\widehat{OR}) = log(0.59) = -0.528
\]</span></p>
<p>und</p>
<p><span class="math display">\[
se_{log(\widehat{OR})} = \sqrt{\frac{1}{20}+\frac{1}{130}+\frac{1}{31}+\frac{1}{119}} = 0.314.
\]</span></p>
<p>Damit können wir ein 95% Konfidenzintervall für das <span class="math inline">\(log(\widehat{OR})\)</span> berechnen:</p>
<p><span class="math display">\[
CI_{0.95_{log(OR)}} = log(\widehat{OR}) \pm 1.96 * se_{log(\widehat{OR})} = -0.528 \pm 1.96 * 0.314 = [-1.143; 0.087].
\]</span></p>
<p>Wenn wir die Grenzen dieses Intervalls exponieren erhalten wir <span class="math inline">\([0.319; 1.091]\)</span>.</p>
<p>Wir können also zu 95% darauf vertrauen, dass das wahre OR im Intervall <span class="math inline">\([0.319; 1.091]\)</span> liegt. Weil dieses Intervall den Nullwert <span class="math inline">\(OR = 1\)</span> enthält, unterscheidet sich dieses nicht statistisch signifikant (bei <span class="math inline">\(\alpha = 0.05\)</span>) von 1. Dieses Resultat ist konsistent zu den Berechnungen mit Proportionen und mit dem RR.</p>
<p>Zuletzt lässt sich für das OR auch ein P-Wert berechnen:</p>
<p><span class="math display">\[
z = \frac{log(\widehat{OR})}{se_{log(\widehat{OR})}} = \frac{-0.528}{0.314} = -1.68
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">1.68</span>) <span class="sc">*</span> <span class="dv">2</span> <span class="co"># * 2 da zweiseitiger P-Wert</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09295732</code></pre>
</div>
</div>
<p>Dieser stimmt mit den Berechnungen mit den Proportionen und dem RR überein.</p>
</section>
</section>
<section id="berechnung-von-or-mit-r" class="level3" data-number="8.6.2">
<h3 data-number="8.6.2" class="anchored" data-anchor-id="berechnung-von-or-mit-r"><span class="header-section-number">8.6.2</span> Berechnung von OR mit <code>R</code></h3>
<p>Wir gehen genau gleich vor wie bei den RR, siehe <a href="#sec-berechnungen-von-rr-mit-r" class="quarto-xref"><span>Section 8.5.2</span></a> . Der einzige Unterschied ist, dass wir statt der Funktion <code>riskratio()</code> die Funktion <code>oddsratio()</code> verwenden.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># laden des Pakets epitools</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epitools)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Berechnung RR, 95% CI und P-Wert</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio</span>(tab, <span class="at">rev =</span> <span class="st">"rows"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$data
              Died
Group           No Yes Total
  Placebo      119  31   150
  Intervention 130  20   150
  Total        249  51   300

$measure
              odds ratio with 95% C.I.
Group          estimate     lower    upper
  Placebo      1.000000        NA       NA
  Intervention 0.593049 0.3156072 1.092475

$p.value
              two-sided
Group          midp.exact fisher.exact chi.square
  Placebo              NA           NA         NA
  Intervention 0.09405295    0.1237165 0.09089263

$correction
[1] FALSE

attr(,"method")
[1] "median-unbiased estimate &amp; mid-p exact CI"</code></pre>
</div>
</div>
<p>Sie sehen unter <code>$data</code>, dass die Tabelle erfolgreich in das richtige Format transformiert wurde. Unter <code>$measure</code> interessiert und nur die zweite Zeile. Sie sehen, dass das OR sowie dessen 95% Konfidenzintervall bis auf kleine Differenzen mit den Berechnungen von Hand übereinstimmen (die Berechnungsmethode ist allerdings eine andere, siehe <code>attr(,"method")</code>). Unter <code>$p.value</code> wird der P-Wert für das OR mit drei verschiedenen Methoden berechnet. Interpretieren Sie den P-Wert unter <code>chi.square</code>, diesen kennen Sie schon vom <span class="math inline">\(\chi^2\)</span>-Test, bzw. vom Proportionstest. Denken Sie daran, dass bei OR gilt: <span class="math inline">\(H_0: OR = 1\)</span>. Die <em>Yate’s continuity correction</em> wird beim Proportionstest standardmässig durchgeführt, hier aber nicht (siehe <code>$correction</code>). Das ist etwas unglücklich, man kann dies aber mit dem zusätzlichen Argument <code>correction = TRUE</code> ändern.</p>
</section>
</section>
<section id="rr-versus-or" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="rr-versus-or"><span class="header-section-number">8.7</span> RR versus OR</h2>
<p>Obwohl die inhaltliche Schlussfolgerung im obigen Beispiel bei OR und RR die gleiche ist, soll man sich bewusst sein, dass OR und RR nicht Synonyme sind. Ein Risiko ist die Anzahl Ereignisse pro Anzahl Personen, während Odds die Anzahl Ereignisse der Anzahl Nicht-Ereignisse gegenüberstellen.</p>
<blockquote class="blockquote">
<p>Grundsätzlich gilt: Je tiefer die Prävalenz des Ereignisses, desto näher beieinander sind Odds und Risiken, bzw. OR und RR.</p>
</blockquote>
<p>Odds versus Risks: In <a href="#fig-plot-odds-versus-risk" class="quarto-xref">Abbildung&nbsp;<span>8.4</span></a> ist erkennbar, dass sich Risiken und Odds bis ca. einer Prävalenz von 5% sehr ähnlich sind. Danach laufen sie immer weiter auseinander. Während ein Risiko maximal den Wert 1 annehmen kann, laufen die Odds (rote Linie) ins Unendliche.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-odds-versus-risk" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-odds-versus-risk-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08_inf_cat_data_files/figure-html/fig-plot-odds-versus-risk-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-odds-versus-risk-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;8.4: Vergleich von Odds und Risks bei unterschiedlicher Prävalenz des Ereignises
</figcaption>
</figure>
</div>
</div>
</div>
<p>RR versus OR: Man kann zeigen, dass <span class="math display">\[   
RR=\frac{OR}{1-R_c+OR\times R_c},
\]</span> mit <span class="math inline">\(R_c\)</span> als dem Risiko in der Kontrollgruppe. Man sieht, dass <span class="math inline">\(RR\approx OR\)</span>, wenn <span class="math inline">\(R_c\)</span> klein.</p>
<p>Anbei ein Beispiel einer Funktion in <code>R</code>, um dies zu veranschaulichen:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>ORtoRR<span class="ot">&lt;-</span><span class="cf">function</span>(or,rc)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    rr<span class="ot">&lt;-</span>or<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>rc<span class="sc">+</span>or<span class="sc">*</span>rc)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(rr)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>    }</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ORtoRR</span>(<span class="at">or=</span><span class="dv">5</span>,<span class="at">rc=</span><span class="fl">0.6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.470588</code></pre>
</div>
</div>
<p>In <a href="#fig-plot-OR-versus-RR" class="quarto-xref">Abbildung&nbsp;<span>8.5</span></a> wird <span class="math inline">\(RR\)</span> als Funktion von <span class="math inline">\(OR\)</span> und Baseline-Risk <span class="math inline">\(R_c\)</span> dargestellt:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plot-OR-versus-RR" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-OR-versus-RR-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08_inf_cat_data_files/figure-html/fig-plot-OR-versus-RR-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-OR-versus-RR-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;8.5: RR als Funktion von OR und Control Risk
</figcaption>
</figure>
</div>
</div>
</div>
<p>Wir sehen: Wenn <span class="math inline">\(OR&lt;1\)</span>, dann <span class="math inline">\(RR&gt;OR\)</span>, wenn <span class="math inline">\(OR&gt;1\)</span>, dann <span class="math inline">\(RR&lt;OR\)</span>. Wenn <span class="math inline">\(OR=1\)</span>, dann <span class="math inline">\(OR=RR\)</span>. Das <span class="math inline">\(RR\)</span> ist also immer näher beim neutralen Wert 1 als das <span class="math inline">\(OR\)</span>.</p>
<p>Soll man auf Grundlage einer Vierfeldertabelle nun OR oder RR berechnen? Dies hängt u.A. von der Frage ab, ob die Berechnung von Risiken überhaupt sinnvoll ist. Das ist z.B. nicht der Fall bei Fallkontrollstudien, weil da das Risko in der Gruppe der <em>Fälle</em> ja immer 100% wäre und in der Gruppe der <em>Kontrollen</em> 0%. Risiken sind auch nicht sinnvoll, wenn die Beobachtungszeiträume der einzelnen Personen unterschiedlich sind. In solchen Situationen berechnet man in der Regel Raten, welche die Beobachtungszeit berücksichtigen. Raten werden in Kapitel 10 behandelt. Schlussendlich ist es auch oft Geschmackssache, bzw. Gewohnheit, ob RR oder OR berechnet werden. Während wir mit Risiken in der Regel besser umgehen können, sind in z.B. England oder den USA Odds gängiger. Odds weisen mathematisch bessere Eigenschaften auf als Risiken. Für mehr Details zum Vergleich von OR und RR wird auf die Fachliteratur verwiesen, z.B. <span class="citation" data-cites="viera2008">(<a href="references.html#ref-viera2008" role="doc-biblioref">Viera 2008</a>)</span>.</p>
</section>
<section id="die-verschiedenen-effektgrössen-im-überblick" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="die-verschiedenen-effektgrössen-im-überblick"><span class="header-section-number">8.8</span> Die verschiedenen Effektgrössen im Überblick</h2>
<ul>
<li><p><span class="math inline">\(\pi \in [0; 1]\)</span>, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\pi\)</span> = 0.5</p></li>
<li><p>RD <span class="math inline">\(\in [-1; 1]\)</span>, <span class="math inline">\(H_0\)</span>: RD = 0</p></li>
<li><p>RR <span class="math inline">\(\in [0; \infty]\)</span>, <span class="math inline">\(H_0\)</span>: RR = 1</p></li>
<li><p>RRR = RR-1 <span class="math inline">\(\in [-1; \infty]\)</span>, <span class="math inline">\(H_0\)</span>: RRR = 0</p></li>
<li><p>NNT <span class="math inline">\(\in[1; \infty]\)</span>, <span class="math inline">\(H_0\)</span>: NNT = <span class="math inline">\(\infty\)</span>&nbsp;</p></li>
<li><p>Odds <span class="math inline">\(\in [0 ; \infty]\)</span>, <span class="math inline">\(H_0\)</span>: Odds = 1</p></li>
<li><p>OR <span class="math inline">\(\in [0: \infty]\)</span>, <span class="math inline">\(H_0\)</span>: OR = 1)</p></li>
<li><p><span class="math inline">\(\log(Odds) \in[-\infty; \infty]\)</span>, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(log(Odds) = 0\)</span>,</p></li>
<li><p>Beachte: <span class="math inline">\(\log(OR) = \log(Odds_1) - \log(Odds_2)\)</span>.</p></li>
</ul>
</section>
<section id="anhang-hilfreiche-r-codes-für-die-analyse-nominaler-daten" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="anhang-hilfreiche-r-codes-für-die-analyse-nominaler-daten"><span class="header-section-number">8.9</span> Anhang: hilfreiche <code>R</code> Codes für die Analyse nominaler Daten</h2>
<p><span class="math inline">\(\chi^2\)</span>-Test</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Daten simulieren </span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">5</span>), <span class="at">byrow =</span> <span class="cn">TRUE</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(m) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"q"</span>, <span class="st">"e"</span>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(m) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"r"</span>, <span class="st">"z"</span>)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">as.table</span>(m)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="fu">counts_to_cases</span>(tab)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Analyse von Proportionen</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">20</span>, <span class="dv">100</span>) <span class="co"># Einstichproben Proportions-Test</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">20</span>, <span class="dv">100</span>, <span class="at">p =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>) <span class="co"># Einstichproben Proportions-Test mit definiertem Nullwert</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">30</span>), <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">100</span>)) <span class="co"># Zweistichproben Proportions-Test</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>OR und RR</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Daten</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1291</span>, <span class="dv">1573</span>, <span class="dv">301</span>, <span class="dv">209</span>), <span class="at">byrow =</span> <span class="cn">FALSE</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(m) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Survived"</span>, <span class="st">"Died"</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(m) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Placebo"</span>, <span class="st">"Treatment"</span>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>table <span class="ot">&lt;-</span> <span class="fu">as.table</span>(m)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="co"># OR und RR</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epitools)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio</span>(table) <span class="co"># Auf Ausrichtung der Tabelle achten!</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="fu">riskratio</span>(table) <span class="co"># Auf Ausrichtung der Tabelle achten!</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-viera2008" class="csl-entry" role="listitem">
Viera, Anthony J. 2008. <span>“Odds ratios and risk ratios: what’s the difference and why does it matter?”</span> <em>Southern Medical Journal</em> 101 (7): 730–34. <a href="https://doi.org/10.1097/SMJ.0b013e31817a7ee4">https://doi.org/10.1097/SMJ.0b013e31817a7ee4</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./07_multiple_linear-regression.html" class="pagination-link" aria-label="Multiple lineare Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09_logistic_regression.html" class="pagination-link" aria-label="Logistische Regression">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>